// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authority.proto

package authoritypb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AppType int32

const (
	AppType_Registry         AppType = 0
	AppType_ServiceProvider  AppType = 1
	AppType_IdentityProvider AppType = 2
)

var AppType_name = map[int32]string{
	0: "Registry",
	1: "ServiceProvider",
	2: "IdentityProvider",
}

var AppType_value = map[string]int32{
	"Registry":         0,
	"ServiceProvider":  1,
	"IdentityProvider": 2,
}

func (x AppType) String() string {
	return proto.EnumName(AppType_name, int32(x))
}

func (AppType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6a5a0640cd66a638, []int{0}
}

type Application struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 AppType  `protobuf:"varint,2,opt,name=type,proto3,enum=authoritypb.AppType" json:"type,omitempty"`
	Label                string   `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	CreateAt             int64    `protobuf:"varint,6,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Application) Reset()         { *m = Application{} }
func (m *Application) String() string { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()    {}
func (*Application) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a5a0640cd66a638, []int{0}
}

func (m *Application) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Application.Unmarshal(m, b)
}
func (m *Application) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Application.Marshal(b, m, deterministic)
}
func (m *Application) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Application.Merge(m, src)
}
func (m *Application) XXX_Size() int {
	return xxx_messageInfo_Application.Size(m)
}
func (m *Application) XXX_DiscardUnknown() {
	xxx_messageInfo_Application.DiscardUnknown(m)
}

var xxx_messageInfo_Application proto.InternalMessageInfo

func (m *Application) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Application) GetType() AppType {
	if m != nil {
		return m.Type
	}
	return AppType_Registry
}

func (m *Application) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Application) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Application) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

type Authentication struct {
	AppName              string   `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Nonce                string   `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Challenge            string   `protobuf:"bytes,3,opt,name=challenge,proto3" json:"challenge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Authentication) Reset()         { *m = Authentication{} }
func (m *Authentication) String() string { return proto.CompactTextString(m) }
func (*Authentication) ProtoMessage()    {}
func (*Authentication) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a5a0640cd66a638, []int{1}
}

func (m *Authentication) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authentication.Unmarshal(m, b)
}
func (m *Authentication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authentication.Marshal(b, m, deterministic)
}
func (m *Authentication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authentication.Merge(m, src)
}
func (m *Authentication) XXX_Size() int {
	return xxx_messageInfo_Authentication.Size(m)
}
func (m *Authentication) XXX_DiscardUnknown() {
	xxx_messageInfo_Authentication.DiscardUnknown(m)
}

var xxx_messageInfo_Authentication proto.InternalMessageInfo

func (m *Authentication) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *Authentication) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *Authentication) GetChallenge() string {
	if m != nil {
		return m.Challenge
	}
	return ""
}

type AppCredentials struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AccessKey            string   `protobuf:"bytes,2,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	AccessSecret         string   `protobuf:"bytes,3,opt,name=access_secret,json=accessSecret,proto3" json:"access_secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppCredentials) Reset()         { *m = AppCredentials{} }
func (m *AppCredentials) String() string { return proto.CompactTextString(m) }
func (*AppCredentials) ProtoMessage()    {}
func (*AppCredentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a5a0640cd66a638, []int{2}
}

func (m *AppCredentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AppCredentials.Unmarshal(m, b)
}
func (m *AppCredentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AppCredentials.Marshal(b, m, deterministic)
}
func (m *AppCredentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppCredentials.Merge(m, src)
}
func (m *AppCredentials) XXX_Size() int {
	return xxx_messageInfo_AppCredentials.Size(m)
}
func (m *AppCredentials) XXX_DiscardUnknown() {
	xxx_messageInfo_AppCredentials.DiscardUnknown(m)
}

var xxx_messageInfo_AppCredentials proto.InternalMessageInfo

func (m *AppCredentials) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AppCredentials) GetAccessKey() string {
	if m != nil {
		return m.AccessKey
	}
	return ""
}

func (m *AppCredentials) GetAccessSecret() string {
	if m != nil {
		return m.AccessSecret
	}
	return ""
}

type RegisterApplicationRequest struct {
	Application          *Application `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RegisterApplicationRequest) Reset()         { *m = RegisterApplicationRequest{} }
func (m *RegisterApplicationRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterApplicationRequest) ProtoMessage()    {}
func (*RegisterApplicationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a5a0640cd66a638, []int{3}
}

func (m *RegisterApplicationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterApplicationRequest.Unmarshal(m, b)
}
func (m *RegisterApplicationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterApplicationRequest.Marshal(b, m, deterministic)
}
func (m *RegisterApplicationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterApplicationRequest.Merge(m, src)
}
func (m *RegisterApplicationRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterApplicationRequest.Size(m)
}
func (m *RegisterApplicationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterApplicationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterApplicationRequest proto.InternalMessageInfo

func (m *RegisterApplicationRequest) GetApplication() *Application {
	if m != nil {
		return m.Application
	}
	return nil
}

type RegisterApplicationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterApplicationResponse) Reset()         { *m = RegisterApplicationResponse{} }
func (m *RegisterApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterApplicationResponse) ProtoMessage()    {}
func (*RegisterApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a5a0640cd66a638, []int{4}
}

func (m *RegisterApplicationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterApplicationResponse.Unmarshal(m, b)
}
func (m *RegisterApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterApplicationResponse.Marshal(b, m, deterministic)
}
func (m *RegisterApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterApplicationResponse.Merge(m, src)
}
func (m *RegisterApplicationResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterApplicationResponse.Size(m)
}
func (m *RegisterApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterApplicationResponse proto.InternalMessageInfo

type GenerateServiceCertificateRequest struct {
	ServiceName          string   `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ApplicationKey       string   `protobuf:"bytes,2,opt,name=application_key,json=applicationKey,proto3" json:"application_key,omitempty"`
	ApplicationSecret    string   `protobuf:"bytes,3,opt,name=application_secret,json=applicationSecret,proto3" json:"application_secret,omitempty"`
	Domains              []string `protobuf:"bytes,4,rep,name=domains,proto3" json:"domains,omitempty"`
	Addresses            []string `protobuf:"bytes,5,rep,name=addresses,proto3" json:"addresses,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,6,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateServiceCertificateRequest) Reset()         { *m = GenerateServiceCertificateRequest{} }
func (m *GenerateServiceCertificateRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateServiceCertificateRequest) ProtoMessage()    {}
func (*GenerateServiceCertificateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a5a0640cd66a638, []int{5}
}

func (m *GenerateServiceCertificateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateServiceCertificateRequest.Unmarshal(m, b)
}
func (m *GenerateServiceCertificateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateServiceCertificateRequest.Marshal(b, m, deterministic)
}
func (m *GenerateServiceCertificateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateServiceCertificateRequest.Merge(m, src)
}
func (m *GenerateServiceCertificateRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateServiceCertificateRequest.Size(m)
}
func (m *GenerateServiceCertificateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateServiceCertificateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateServiceCertificateRequest proto.InternalMessageInfo

func (m *GenerateServiceCertificateRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *GenerateServiceCertificateRequest) GetApplicationKey() string {
	if m != nil {
		return m.ApplicationKey
	}
	return ""
}

func (m *GenerateServiceCertificateRequest) GetApplicationSecret() string {
	if m != nil {
		return m.ApplicationSecret
	}
	return ""
}

func (m *GenerateServiceCertificateRequest) GetDomains() []string {
	if m != nil {
		return m.Domains
	}
	return nil
}

func (m *GenerateServiceCertificateRequest) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *GenerateServiceCertificateRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type GenerateServiceCertificateResponse struct {
	CertificateBytes     []byte   `protobuf:"bytes,1,opt,name=certificateBytes,proto3" json:"certificateBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateServiceCertificateResponse) Reset()         { *m = GenerateServiceCertificateResponse{} }
func (m *GenerateServiceCertificateResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateServiceCertificateResponse) ProtoMessage()    {}
func (*GenerateServiceCertificateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a5a0640cd66a638, []int{6}
}

func (m *GenerateServiceCertificateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateServiceCertificateResponse.Unmarshal(m, b)
}
func (m *GenerateServiceCertificateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateServiceCertificateResponse.Marshal(b, m, deterministic)
}
func (m *GenerateServiceCertificateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateServiceCertificateResponse.Merge(m, src)
}
func (m *GenerateServiceCertificateResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateServiceCertificateResponse.Size(m)
}
func (m *GenerateServiceCertificateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateServiceCertificateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateServiceCertificateResponse proto.InternalMessageInfo

func (m *GenerateServiceCertificateResponse) GetCertificateBytes() []byte {
	if m != nil {
		return m.CertificateBytes
	}
	return nil
}

type AuthenticateRequest struct {
	Authentication       *Authentication `protobuf:"bytes,1,opt,name=authentication,proto3" json:"authentication,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a5a0640cd66a638, []int{7}
}

func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(m, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetAuthentication() *Authentication {
	if m != nil {
		return m.Authentication
	}
	return nil
}

type AuthenticateResponse struct {
	Nonce                string   `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a5a0640cd66a638, []int{8}
}

func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(m, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

func (m *AuthenticateResponse) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *AuthenticateResponse) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func init() {
	proto.RegisterEnum("authoritypb.AppType", AppType_name, AppType_value)
	proto.RegisterType((*Application)(nil), "authoritypb.Application")
	proto.RegisterType((*Authentication)(nil), "authoritypb.Authentication")
	proto.RegisterType((*AppCredentials)(nil), "authoritypb.AppCredentials")
	proto.RegisterType((*RegisterApplicationRequest)(nil), "authoritypb.RegisterApplicationRequest")
	proto.RegisterType((*RegisterApplicationResponse)(nil), "authoritypb.RegisterApplicationResponse")
	proto.RegisterType((*GenerateServiceCertificateRequest)(nil), "authoritypb.GenerateServiceCertificateRequest")
	proto.RegisterType((*GenerateServiceCertificateResponse)(nil), "authoritypb.GenerateServiceCertificateResponse")
	proto.RegisterType((*AuthenticateRequest)(nil), "authoritypb.AuthenticateRequest")
	proto.RegisterType((*AuthenticateResponse)(nil), "authoritypb.AuthenticateResponse")
}

func init() { proto.RegisterFile("authority.proto", fileDescriptor_6a5a0640cd66a638) }

var fileDescriptor_6a5a0640cd66a638 = []byte{
	// 670 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xfd, 0xdc, 0x24, 0x6d, 0x72, 0x93, 0x2f, 0x0d, 0x53, 0x2f, 0xdc, 0xb4, 0x15, 0xae, 0x59,
	0x34, 0xaa, 0x44, 0x22, 0xca, 0xae, 0xbb, 0xb4, 0x0b, 0x84, 0x2a, 0xa1, 0xca, 0x65, 0x81, 0xd8,
	0x44, 0x13, 0xfb, 0x92, 0x58, 0xb8, 0xf6, 0x30, 0x33, 0x89, 0xe4, 0x2d, 0x3b, 0xd6, 0xec, 0x11,
	0x4f, 0xc1, 0x8b, 0xf0, 0x0a, 0xbc, 0x02, 0x7b, 0xe4, 0x99, 0x69, 0x32, 0x2e, 0xfd, 0x61, 0x97,
	0x39, 0xf7, 0xde, 0x39, 0x67, 0xce, 0x3d, 0x31, 0x6c, 0xd3, 0x85, 0x9c, 0xe7, 0x3c, 0x91, 0xc5,
	0x90, 0xf1, 0x5c, 0xe6, 0xa4, 0xbd, 0x02, 0xd8, 0xb4, 0xbf, 0x3f, 0xcb, 0xf3, 0x59, 0x8a, 0x23,
	0xca, 0x92, 0x11, 0xcd, 0xb2, 0x5c, 0x52, 0x99, 0xe4, 0x99, 0xd0, 0xad, 0xc1, 0x77, 0x07, 0xda,
	0x63, 0xc6, 0xd2, 0x24, 0x52, 0x30, 0x21, 0x50, 0xcf, 0xe8, 0x35, 0x7a, 0x8e, 0xef, 0x0c, 0x5a,
	0xa1, 0xfa, 0x4d, 0x06, 0x50, 0x97, 0x05, 0x43, 0x6f, 0xc3, 0x77, 0x06, 0xdd, 0x13, 0x77, 0x68,
	0xdd, 0x3e, 0x1c, 0x33, 0xf6, 0xb6, 0x60, 0x18, 0xaa, 0x0e, 0xe2, 0x42, 0x23, 0xa5, 0x53, 0x4c,
	0xbd, 0xba, 0x1a, 0xd7, 0x07, 0xe2, 0x43, 0x3b, 0x46, 0x11, 0xf1, 0x84, 0x95, 0x14, 0x5e, 0x43,
	0xd5, 0x6c, 0x88, 0xec, 0x41, 0x2b, 0xe2, 0x48, 0x25, 0x4e, 0xa8, 0xf4, 0x36, 0x7d, 0x67, 0x50,
	0x0b, 0x9b, 0x1a, 0x18, 0xcb, 0x60, 0x02, 0xdd, 0xf1, 0x42, 0xce, 0x31, 0x93, 0x37, 0x22, 0x77,
	0xa1, 0x49, 0x19, 0x9b, 0x58, 0x42, 0xb7, 0x28, 0x63, 0x6f, 0x4a, 0xad, 0x2e, 0x34, 0xb2, 0x3c,
	0x8b, 0xb4, 0xd8, 0x56, 0xa8, 0x0f, 0x64, 0x1f, 0x5a, 0xd1, 0x9c, 0xa6, 0x29, 0x66, 0x33, 0xf4,
	0x6a, 0xaa, 0xb2, 0x06, 0x82, 0x39, 0x74, 0xc7, 0x8c, 0x9d, 0x73, 0x8c, 0x4b, 0x0e, 0x9a, 0x8a,
	0x3b, 0x5d, 0x38, 0x00, 0xa0, 0x51, 0x84, 0x42, 0x4c, 0x3e, 0x62, 0x61, 0xae, 0x6f, 0x69, 0xe4,
	0x02, 0x0b, 0xf2, 0x0c, 0xfe, 0x37, 0x65, 0x81, 0x11, 0x47, 0x69, 0x68, 0x3a, 0x1a, 0xbc, 0x52,
	0x58, 0xf0, 0x0e, 0xfa, 0x21, 0xce, 0x12, 0x21, 0x91, 0x5b, 0xa6, 0x87, 0xf8, 0x69, 0x81, 0x42,
	0x92, 0x53, 0x68, 0xd3, 0x35, 0xaa, 0xc8, 0xdb, 0x27, 0xde, 0x6d, 0xbb, 0x57, 0x53, 0x76, 0x73,
	0x70, 0x00, 0x7b, 0x77, 0xde, 0x2c, 0x58, 0x9e, 0x09, 0x0c, 0x7e, 0x3b, 0x70, 0xf8, 0x0a, 0x33,
	0xe4, 0x54, 0xe2, 0x15, 0xf2, 0x65, 0x12, 0xe1, 0x39, 0x72, 0x99, 0x7c, 0x28, 0x1b, 0xf1, 0x46,
	0xc0, 0x21, 0x74, 0x84, 0x2e, 0xda, 0xde, 0xb6, 0x0d, 0xa6, 0xfc, 0x3d, 0x82, 0x6d, 0x8b, 0xd6,
	0xb2, 0xa2, 0x6b, 0xc1, 0xa5, 0x1f, 0xcf, 0x81, 0xd8, 0x8d, 0x15, 0x53, 0x9e, 0x58, 0x15, 0xed,
	0x0c, 0xf1, 0x60, 0x2b, 0xce, 0xaf, 0x69, 0x92, 0x09, 0xaf, 0xee, 0xd7, 0xca, 0x8d, 0x9a, 0x63,
	0xb9, 0x3b, 0x1a, 0xc7, 0x1c, 0x85, 0x40, 0xe1, 0x35, 0x54, 0x6d, 0x0d, 0x94, 0x5b, 0x61, 0x8b,
	0x69, 0x9a, 0x44, 0x4a, 0x4a, 0x19, 0x9d, 0x4e, 0xd8, 0xd2, 0xc8, 0x05, 0x16, 0xc1, 0x25, 0x04,
	0x0f, 0x3d, 0x5b, 0xbb, 0x43, 0x8e, 0xa1, 0x17, 0xad, 0xe1, 0xb3, 0x42, 0xa2, 0x50, 0x6f, 0xef,
	0x84, 0x7f, 0xe1, 0xc1, 0x7b, 0xd8, 0xb1, 0xd2, 0xb8, 0xb2, 0xee, 0x1c, 0xba, 0xb4, 0x12, 0x52,
	0xb3, 0xbe, 0xbd, 0xea, 0xfa, 0x2a, 0x2d, 0xe1, 0xad, 0x91, 0xe0, 0x0c, 0xdc, 0xea, 0xdd, 0x46,
	0xdf, 0x2a, 0xd4, 0x8e, 0x1d, 0x6a, 0x17, 0x1a, 0x4b, 0x9a, 0x26, 0xb1, 0x5a, 0x40, 0x33, 0xd4,
	0x87, 0xe3, 0x33, 0xd8, 0x32, 0xff, 0x49, 0xd2, 0x81, 0xa6, 0xce, 0x04, 0x2f, 0x7a, 0xff, 0x91,
	0x1d, 0xd8, 0x36, 0x16, 0x5c, 0xf2, 0x7c, 0x99, 0xc4, 0xc8, 0x7b, 0x0e, 0x71, 0xa1, 0xf7, 0x5a,
	0xa5, 0x5e, 0x16, 0x2b, 0x74, 0xe3, 0xe4, 0x47, 0x0d, 0x7a, 0xe3, 0x1b, 0xd9, 0x66, 0x88, 0x7c,
	0x71, 0x60, 0xe7, 0x8e, 0x88, 0x91, 0xa3, 0xca, 0x0b, 0xef, 0x8f, 0x77, 0x7f, 0xf0, 0x78, 0xa3,
	0x49, 0xeb, 0xd3, 0xcf, 0x3f, 0x7f, 0x7d, 0xdd, 0xd8, 0x0d, 0x5c, 0xf5, 0xd1, 0x5a, 0xbe, 0x18,
	0x51, 0xc6, 0x46, 0xdc, 0x0c, 0x9c, 0x3a, 0xc7, 0xe4, 0x9b, 0x03, 0xfd, 0xfb, 0xf7, 0x4a, 0x86,
	0x15, 0xa6, 0x47, 0x73, 0xdf, 0x1f, 0xfd, 0x73, 0xff, 0x43, 0x02, 0xcb, 0xa8, 0x8c, 0x66, 0x28,
	0x4b, 0x81, 0x0b, 0xe8, 0xd8, 0x9b, 0x24, 0xfe, 0x7d, 0x31, 0x58, 0x69, 0x38, 0x7c, 0xa0, 0xc3,
	0xb0, 0xfa, 0x8a, 0xb5, 0x4f, 0x3c, 0x9b, 0xd5, 0x8a, 0x10, 0x4e, 0x37, 0xd5, 0x47, 0xfd, 0xe5,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x65, 0x48, 0x27, 0xf4, 0x12, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthorityServiceClient is the client API for AuthorityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthorityServiceClient interface {
	RegisterApplication(ctx context.Context, in *RegisterApplicationRequest, opts ...grpc.CallOption) (*RegisterApplicationResponse, error)
	GenerateServiceCertificate(ctx context.Context, in *GenerateServiceCertificateRequest, opts ...grpc.CallOption) (*GenerateServiceCertificateResponse, error)
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
}

type authorityServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthorityServiceClient(cc *grpc.ClientConn) AuthorityServiceClient {
	return &authorityServiceClient{cc}
}

func (c *authorityServiceClient) RegisterApplication(ctx context.Context, in *RegisterApplicationRequest, opts ...grpc.CallOption) (*RegisterApplicationResponse, error) {
	out := new(RegisterApplicationResponse)
	err := c.cc.Invoke(ctx, "/authoritypb.AuthorityService/RegisterApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorityServiceClient) GenerateServiceCertificate(ctx context.Context, in *GenerateServiceCertificateRequest, opts ...grpc.CallOption) (*GenerateServiceCertificateResponse, error) {
	out := new(GenerateServiceCertificateResponse)
	err := c.cc.Invoke(ctx, "/authoritypb.AuthorityService/GenerateServiceCertificate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorityServiceClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, "/authoritypb.AuthorityService/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorityServiceServer is the server API for AuthorityService service.
type AuthorityServiceServer interface {
	RegisterApplication(context.Context, *RegisterApplicationRequest) (*RegisterApplicationResponse, error)
	GenerateServiceCertificate(context.Context, *GenerateServiceCertificateRequest) (*GenerateServiceCertificateResponse, error)
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
}

// UnimplementedAuthorityServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthorityServiceServer struct {
}

func (*UnimplementedAuthorityServiceServer) RegisterApplication(ctx context.Context, req *RegisterApplicationRequest) (*RegisterApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterApplication not implemented")
}
func (*UnimplementedAuthorityServiceServer) GenerateServiceCertificate(ctx context.Context, req *GenerateServiceCertificateRequest) (*GenerateServiceCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateServiceCertificate not implemented")
}
func (*UnimplementedAuthorityServiceServer) Authenticate(ctx context.Context, req *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}

func RegisterAuthorityServiceServer(s *grpc.Server, srv AuthorityServiceServer) {
	s.RegisterService(&_AuthorityService_serviceDesc, srv)
}

func _AuthorityService_RegisterApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterApplicationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorityServiceServer).RegisterApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authoritypb.AuthorityService/RegisterApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorityServiceServer).RegisterApplication(ctx, req.(*RegisterApplicationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorityService_GenerateServiceCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateServiceCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorityServiceServer).GenerateServiceCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authoritypb.AuthorityService/GenerateServiceCertificate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorityServiceServer).GenerateServiceCertificate(ctx, req.(*GenerateServiceCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorityService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorityServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authoritypb.AuthorityService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorityServiceServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthorityService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authoritypb.AuthorityService",
	HandlerType: (*AuthorityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterApplication",
			Handler:    _AuthorityService_RegisterApplication_Handler,
		},
		{
			MethodName: "GenerateServiceCertificate",
			Handler:    _AuthorityService_GenerateServiceCertificate_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _AuthorityService_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authority.proto",
}
