// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package authpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type JWTPurpose int32

const (
	JWTPurpose_AUTHENTICATION   JWTPurpose = 0
	JWTPurpose_RESOURCES_ACCESS JWTPurpose = 1
	JWTPurpose_VALIDATION       JWTPurpose = 2
)

var JWTPurpose_name = map[int32]string{
	0: "AUTHENTICATION",
	1: "RESOURCES_ACCESS",
	2: "VALIDATION",
}

var JWTPurpose_value = map[string]int32{
	"AUTHENTICATION":   0,
	"RESOURCES_ACCESS": 1,
	"VALIDATION":       2,
}

func (x JWTPurpose) String() string {
	return proto.EnumName(JWTPurpose_name, int32(x))
}

func (JWTPurpose) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

type JWTState int32

const (
	JWTState_VALID         JWTState = 0
	JWTState_NOT_VALID     JWTState = 1
	JWTState_EXPIRED       JWTState = 2
	JWTState_REVOKED       JWTState = 3
	JWTState_NOT_SIGNED    JWTState = 4
	JWTState_NOT_EFFECTIVE JWTState = 5
)

var JWTState_name = map[int32]string{
	0: "VALID",
	1: "NOT_VALID",
	2: "EXPIRED",
	3: "REVOKED",
	4: "NOT_SIGNED",
	5: "NOT_EFFECTIVE",
}

var JWTState_value = map[string]int32{
	"VALID":         0,
	"NOT_VALID":     1,
	"EXPIRED":       2,
	"REVOKED":       3,
	"NOT_SIGNED":    4,
	"NOT_EFFECTIVE": 5,
}

func (x JWTState) String() string {
	return proto.EnumName(JWTState_name, int32(x))
}

func (JWTState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

type EventAction int32

const (
	EventAction_Delete EventAction = 0
	EventAction_Save   EventAction = 1
)

var EventAction_name = map[int32]string{
	0: "Delete",
	1: "Save",
}

var EventAction_value = map[string]int32{
	"Delete": 0,
	"Save":   1,
}

func (x EventAction) String() string {
	return proto.EnumName(EventAction_name, int32(x))
}

func (EventAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

type JWTHeader struct {
	Typ                  string   `protobuf:"bytes,1,opt,name=typ,proto3" json:"typ,omitempty"`
	Alg                  string   `protobuf:"bytes,2,opt,name=alg,proto3" json:"alg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JWTHeader) Reset()         { *m = JWTHeader{} }
func (m *JWTHeader) String() string { return proto.CompactTextString(m) }
func (*JWTHeader) ProtoMessage()    {}
func (*JWTHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *JWTHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWTHeader.Unmarshal(m, b)
}
func (m *JWTHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWTHeader.Marshal(b, m, deterministic)
}
func (m *JWTHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWTHeader.Merge(m, src)
}
func (m *JWTHeader) XXX_Size() int {
	return xxx_messageInfo_JWTHeader.Size(m)
}
func (m *JWTHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_JWTHeader.DiscardUnknown(m)
}

var xxx_messageInfo_JWTHeader proto.InternalMessageInfo

func (m *JWTHeader) GetTyp() string {
	if m != nil {
		return m.Typ
	}
	return ""
}

func (m *JWTHeader) GetAlg() string {
	if m != nil {
		return m.Alg
	}
	return ""
}

type Claims struct {
	Iss                  string   `protobuf:"bytes,1,opt,name=iss,proto3" json:"iss,omitempty"`
	Sub                  string   `protobuf:"bytes,2,opt,name=sub,proto3" json:"sub,omitempty"`
	Aud                  string   `protobuf:"bytes,3,opt,name=aud,proto3" json:"aud,omitempty"`
	Exp                  int64    `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	Nbf                  int64    `protobuf:"varint,5,opt,name=nbf,proto3" json:"nbf,omitempty"`
	Iat                  int64    `protobuf:"varint,6,opt,name=iat,proto3" json:"iat,omitempty"`
	Jti                  string   `protobuf:"bytes,7,opt,name=jti,proto3" json:"jti,omitempty"`
	Version              string   `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	Scope                []string `protobuf:"bytes,9,rep,name=scope,proto3" json:"scope,omitempty"`
	Origin               string   `protobuf:"bytes,10,opt,name=origin,proto3" json:"origin,omitempty"`
	Data                 string   `protobuf:"bytes,11,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Claims) Reset()         { *m = Claims{} }
func (m *Claims) String() string { return proto.CompactTextString(m) }
func (*Claims) ProtoMessage()    {}
func (*Claims) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *Claims) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Claims.Unmarshal(m, b)
}
func (m *Claims) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Claims.Marshal(b, m, deterministic)
}
func (m *Claims) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Claims.Merge(m, src)
}
func (m *Claims) XXX_Size() int {
	return xxx_messageInfo_Claims.Size(m)
}
func (m *Claims) XXX_DiscardUnknown() {
	xxx_messageInfo_Claims.DiscardUnknown(m)
}

var xxx_messageInfo_Claims proto.InternalMessageInfo

func (m *Claims) GetIss() string {
	if m != nil {
		return m.Iss
	}
	return ""
}

func (m *Claims) GetSub() string {
	if m != nil {
		return m.Sub
	}
	return ""
}

func (m *Claims) GetAud() string {
	if m != nil {
		return m.Aud
	}
	return ""
}

func (m *Claims) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *Claims) GetNbf() int64 {
	if m != nil {
		return m.Nbf
	}
	return 0
}

func (m *Claims) GetIat() int64 {
	if m != nil {
		return m.Iat
	}
	return 0
}

func (m *Claims) GetJti() string {
	if m != nil {
		return m.Jti
	}
	return ""
}

func (m *Claims) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Claims) GetScope() []string {
	if m != nil {
		return m.Scope
	}
	return nil
}

func (m *Claims) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Claims) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type JWT struct {
	Header               *JWTHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Claims               *Claims    `protobuf:"bytes,2,opt,name=claims,proto3" json:"claims,omitempty"`
	Signature            string     `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *JWT) Reset()         { *m = JWT{} }
func (m *JWT) String() string { return proto.CompactTextString(m) }
func (*JWT) ProtoMessage()    {}
func (*JWT) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *JWT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JWT.Unmarshal(m, b)
}
func (m *JWT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JWT.Marshal(b, m, deterministic)
}
func (m *JWT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JWT.Merge(m, src)
}
func (m *JWT) XXX_Size() int {
	return xxx_messageInfo_JWT.Size(m)
}
func (m *JWT) XXX_DiscardUnknown() {
	xxx_messageInfo_JWT.DiscardUnknown(m)
}

var xxx_messageInfo_JWT proto.InternalMessageInfo

func (m *JWT) GetHeader() *JWTHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *JWT) GetClaims() *Claims {
	if m != nil {
		return m.Claims
	}
	return nil
}

func (m *JWT) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type Credentials struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credentials) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type JwtInfo struct {
	Jti                  string   `protobuf:"bytes,1,opt,name=jti,proto3" json:"jti,omitempty"`
	Nbf                  int64    `protobuf:"varint,2,opt,name=nbf,proto3" json:"nbf,omitempty"`
	Exp                  int64    `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
	State                JWTState `protobuf:"varint,4,opt,name=state,proto3,enum=authpb.JWTState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JwtInfo) Reset()         { *m = JwtInfo{} }
func (m *JwtInfo) String() string { return proto.CompactTextString(m) }
func (*JwtInfo) ProtoMessage()    {}
func (*JwtInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *JwtInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JwtInfo.Unmarshal(m, b)
}
func (m *JwtInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JwtInfo.Marshal(b, m, deterministic)
}
func (m *JwtInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JwtInfo.Merge(m, src)
}
func (m *JwtInfo) XXX_Size() int {
	return xxx_messageInfo_JwtInfo.Size(m)
}
func (m *JwtInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_JwtInfo.DiscardUnknown(m)
}

var xxx_messageInfo_JwtInfo proto.InternalMessageInfo

func (m *JwtInfo) GetJti() string {
	if m != nil {
		return m.Jti
	}
	return ""
}

func (m *JwtInfo) GetNbf() int64 {
	if m != nil {
		return m.Nbf
	}
	return 0
}

func (m *JwtInfo) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *JwtInfo) GetState() JWTState {
	if m != nil {
		return m.State
	}
	return JWTState_VALID
}

type JwtEvent struct {
	Action               EventAction `protobuf:"varint,1,opt,name=action,proto3,enum=authpb.EventAction" json:"action,omitempty"`
	Info                 *JwtInfo    `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *JwtEvent) Reset()         { *m = JwtEvent{} }
func (m *JwtEvent) String() string { return proto.CompactTextString(m) }
func (*JwtEvent) ProtoMessage()    {}
func (*JwtEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *JwtEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JwtEvent.Unmarshal(m, b)
}
func (m *JwtEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JwtEvent.Marshal(b, m, deterministic)
}
func (m *JwtEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JwtEvent.Merge(m, src)
}
func (m *JwtEvent) XXX_Size() int {
	return xxx_messageInfo_JwtEvent.Size(m)
}
func (m *JwtEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_JwtEvent.DiscardUnknown(m)
}

var xxx_messageInfo_JwtEvent proto.InternalMessageInfo

func (m *JwtEvent) GetAction() EventAction {
	if m != nil {
		return m.Action
	}
	return EventAction_Delete
}

func (m *JwtEvent) GetInfo() *JwtInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type FeedResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Jti                  string   `protobuf:"bytes,2,opt,name=jti,proto3" json:"jti,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedResponse) Reset()         { *m = FeedResponse{} }
func (m *FeedResponse) String() string { return proto.CompactTextString(m) }
func (*FeedResponse) ProtoMessage()    {}
func (*FeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *FeedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedResponse.Unmarshal(m, b)
}
func (m *FeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedResponse.Marshal(b, m, deterministic)
}
func (m *FeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedResponse.Merge(m, src)
}
func (m *FeedResponse) XXX_Size() int {
	return xxx_messageInfo_FeedResponse.Size(m)
}
func (m *FeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeedResponse proto.InternalMessageInfo

func (m *FeedResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *FeedResponse) GetJti() string {
	if m != nil {
		return m.Jti
	}
	return ""
}

type FindJWTRequest struct {
	Jti                  string   `protobuf:"bytes,1,opt,name=jti,proto3" json:"jti,omitempty"`
	Signature            string   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindJWTRequest) Reset()         { *m = FindJWTRequest{} }
func (m *FindJWTRequest) String() string { return proto.CompactTextString(m) }
func (*FindJWTRequest) ProtoMessage()    {}
func (*FindJWTRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{7}
}

func (m *FindJWTRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindJWTRequest.Unmarshal(m, b)
}
func (m *FindJWTRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindJWTRequest.Marshal(b, m, deterministic)
}
func (m *FindJWTRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindJWTRequest.Merge(m, src)
}
func (m *FindJWTRequest) XXX_Size() int {
	return xxx_messageInfo_FindJWTRequest.Size(m)
}
func (m *FindJWTRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindJWTRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindJWTRequest proto.InternalMessageInfo

func (m *FindJWTRequest) GetJti() string {
	if m != nil {
		return m.Jti
	}
	return ""
}

func (m *FindJWTRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type FindJWTResponse struct {
	Found                string   `protobuf:"bytes,1,opt,name=found,proto3" json:"found,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindJWTResponse) Reset()         { *m = FindJWTResponse{} }
func (m *FindJWTResponse) String() string { return proto.CompactTextString(m) }
func (*FindJWTResponse) ProtoMessage()    {}
func (*FindJWTResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{8}
}

func (m *FindJWTResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindJWTResponse.Unmarshal(m, b)
}
func (m *FindJWTResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindJWTResponse.Marshal(b, m, deterministic)
}
func (m *FindJWTResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindJWTResponse.Merge(m, src)
}
func (m *FindJWTResponse) XXX_Size() int {
	return xxx_messageInfo_FindJWTResponse.Size(m)
}
func (m *FindJWTResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindJWTResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindJWTResponse proto.InternalMessageInfo

func (m *FindJWTResponse) GetFound() string {
	if m != nil {
		return m.Found
	}
	return ""
}

type DeleteJWTRequest struct {
	Jti                  string   `protobuf:"bytes,1,opt,name=jti,proto3" json:"jti,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteJWTRequest) Reset()         { *m = DeleteJWTRequest{} }
func (m *DeleteJWTRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteJWTRequest) ProtoMessage()    {}
func (*DeleteJWTRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{9}
}

func (m *DeleteJWTRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteJWTRequest.Unmarshal(m, b)
}
func (m *DeleteJWTRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteJWTRequest.Marshal(b, m, deterministic)
}
func (m *DeleteJWTRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteJWTRequest.Merge(m, src)
}
func (m *DeleteJWTRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteJWTRequest.Size(m)
}
func (m *DeleteJWTRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteJWTRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteJWTRequest proto.InternalMessageInfo

func (m *DeleteJWTRequest) GetJti() string {
	if m != nil {
		return m.Jti
	}
	return ""
}

type DeleteJWTResponse struct {
	Count                uint32   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteJWTResponse) Reset()         { *m = DeleteJWTResponse{} }
func (m *DeleteJWTResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteJWTResponse) ProtoMessage()    {}
func (*DeleteJWTResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{10}
}

func (m *DeleteJWTResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteJWTResponse.Unmarshal(m, b)
}
func (m *DeleteJWTResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteJWTResponse.Marshal(b, m, deterministic)
}
func (m *DeleteJWTResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteJWTResponse.Merge(m, src)
}
func (m *DeleteJWTResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteJWTResponse.Size(m)
}
func (m *DeleteJWTResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteJWTResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteJWTResponse proto.InternalMessageInfo

func (m *DeleteJWTResponse) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ListenRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListenRequest) Reset()         { *m = ListenRequest{} }
func (m *ListenRequest) String() string { return proto.CompactTextString(m) }
func (*ListenRequest) ProtoMessage()    {}
func (*ListenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{11}
}

func (m *ListenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListenRequest.Unmarshal(m, b)
}
func (m *ListenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListenRequest.Marshal(b, m, deterministic)
}
func (m *ListenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListenRequest.Merge(m, src)
}
func (m *ListenRequest) XXX_Size() int {
	return xxx_messageInfo_ListenRequest.Size(m)
}
func (m *ListenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListenRequest proto.InternalMessageInfo

type CreateCredentialsRequest struct {
	Credentials          *Credentials `protobuf:"bytes,1,opt,name=credentials,proto3" json:"credentials,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateCredentialsRequest) Reset()         { *m = CreateCredentialsRequest{} }
func (m *CreateCredentialsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCredentialsRequest) ProtoMessage()    {}
func (*CreateCredentialsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{12}
}

func (m *CreateCredentialsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCredentialsRequest.Unmarshal(m, b)
}
func (m *CreateCredentialsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCredentialsRequest.Marshal(b, m, deterministic)
}
func (m *CreateCredentialsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCredentialsRequest.Merge(m, src)
}
func (m *CreateCredentialsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCredentialsRequest.Size(m)
}
func (m *CreateCredentialsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCredentialsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCredentialsRequest proto.InternalMessageInfo

func (m *CreateCredentialsRequest) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type CreateCredentialsResponse struct {
	UserTaken            bool     `protobuf:"varint,1,opt,name=user_taken,json=userTaken,proto3" json:"user_taken,omitempty"`
	EmailTaken           bool     `protobuf:"varint,2,opt,name=email_taken,json=emailTaken,proto3" json:"email_taken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCredentialsResponse) Reset()         { *m = CreateCredentialsResponse{} }
func (m *CreateCredentialsResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCredentialsResponse) ProtoMessage()    {}
func (*CreateCredentialsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{13}
}

func (m *CreateCredentialsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCredentialsResponse.Unmarshal(m, b)
}
func (m *CreateCredentialsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCredentialsResponse.Marshal(b, m, deterministic)
}
func (m *CreateCredentialsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCredentialsResponse.Merge(m, src)
}
func (m *CreateCredentialsResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCredentialsResponse.Size(m)
}
func (m *CreateCredentialsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCredentialsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCredentialsResponse proto.InternalMessageInfo

func (m *CreateCredentialsResponse) GetUserTaken() bool {
	if m != nil {
		return m.UserTaken
	}
	return false
}

func (m *CreateCredentialsResponse) GetEmailTaken() bool {
	if m != nil {
		return m.EmailTaken
	}
	return false
}

type AuthenticateRequest struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{14}
}

func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(m, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *AuthenticateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetTokenResponse struct {
	Jwt                  *JWT     `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Code                 uint32   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTokenResponse) Reset()         { *m = GetTokenResponse{} }
func (m *GetTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetTokenResponse) ProtoMessage()    {}
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{15}
}

func (m *GetTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTokenResponse.Unmarshal(m, b)
}
func (m *GetTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTokenResponse.Merge(m, src)
}
func (m *GetTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetTokenResponse.Size(m)
}
func (m *GetTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTokenResponse proto.InternalMessageInfo

func (m *GetTokenResponse) GetJwt() *JWT {
	if m != nil {
		return m.Jwt
	}
	return nil
}

func (m *GetTokenResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type ValidateEmailRequest struct {
	Info                 string   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateEmailRequest) Reset()         { *m = ValidateEmailRequest{} }
func (m *ValidateEmailRequest) String() string { return proto.CompactTextString(m) }
func (*ValidateEmailRequest) ProtoMessage()    {}
func (*ValidateEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{16}
}

func (m *ValidateEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateEmailRequest.Unmarshal(m, b)
}
func (m *ValidateEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateEmailRequest.Marshal(b, m, deterministic)
}
func (m *ValidateEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateEmailRequest.Merge(m, src)
}
func (m *ValidateEmailRequest) XXX_Size() int {
	return xxx_messageInfo_ValidateEmailRequest.Size(m)
}
func (m *ValidateEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateEmailRequest proto.InternalMessageInfo

func (m *ValidateEmailRequest) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type ValidateEmailResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidateEmailResponse) Reset()         { *m = ValidateEmailResponse{} }
func (m *ValidateEmailResponse) String() string { return proto.CompactTextString(m) }
func (*ValidateEmailResponse) ProtoMessage()    {}
func (*ValidateEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{17}
}

func (m *ValidateEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidateEmailResponse.Unmarshal(m, b)
}
func (m *ValidateEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidateEmailResponse.Marshal(b, m, deterministic)
}
func (m *ValidateEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidateEmailResponse.Merge(m, src)
}
func (m *ValidateEmailResponse) XXX_Size() int {
	return xxx_messageInfo_ValidateEmailResponse.Size(m)
}
func (m *ValidateEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidateEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ValidateEmailResponse proto.InternalMessageInfo

type TriggerEmailValidationRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TriggerEmailValidationRequest) Reset()         { *m = TriggerEmailValidationRequest{} }
func (m *TriggerEmailValidationRequest) String() string { return proto.CompactTextString(m) }
func (*TriggerEmailValidationRequest) ProtoMessage()    {}
func (*TriggerEmailValidationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{18}
}

func (m *TriggerEmailValidationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriggerEmailValidationRequest.Unmarshal(m, b)
}
func (m *TriggerEmailValidationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriggerEmailValidationRequest.Marshal(b, m, deterministic)
}
func (m *TriggerEmailValidationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriggerEmailValidationRequest.Merge(m, src)
}
func (m *TriggerEmailValidationRequest) XXX_Size() int {
	return xxx_messageInfo_TriggerEmailValidationRequest.Size(m)
}
func (m *TriggerEmailValidationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TriggerEmailValidationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TriggerEmailValidationRequest proto.InternalMessageInfo

func (m *TriggerEmailValidationRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type TriggerEmailValidationResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TriggerEmailValidationResponse) Reset()         { *m = TriggerEmailValidationResponse{} }
func (m *TriggerEmailValidationResponse) String() string { return proto.CompactTextString(m) }
func (*TriggerEmailValidationResponse) ProtoMessage()    {}
func (*TriggerEmailValidationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{19}
}

func (m *TriggerEmailValidationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TriggerEmailValidationResponse.Unmarshal(m, b)
}
func (m *TriggerEmailValidationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TriggerEmailValidationResponse.Marshal(b, m, deterministic)
}
func (m *TriggerEmailValidationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TriggerEmailValidationResponse.Merge(m, src)
}
func (m *TriggerEmailValidationResponse) XXX_Size() int {
	return xxx_messageInfo_TriggerEmailValidationResponse.Size(m)
}
func (m *TriggerEmailValidationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TriggerEmailValidationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TriggerEmailValidationResponse proto.InternalMessageInfo

type RevokeTokenRequest struct {
	Jwt                  *JWT     `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeTokenRequest) Reset()         { *m = RevokeTokenRequest{} }
func (m *RevokeTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RevokeTokenRequest) ProtoMessage()    {}
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{20}
}

func (m *RevokeTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeTokenRequest.Unmarshal(m, b)
}
func (m *RevokeTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeTokenRequest.Marshal(b, m, deterministic)
}
func (m *RevokeTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeTokenRequest.Merge(m, src)
}
func (m *RevokeTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RevokeTokenRequest.Size(m)
}
func (m *RevokeTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeTokenRequest proto.InternalMessageInfo

func (m *RevokeTokenRequest) GetJwt() *JWT {
	if m != nil {
		return m.Jwt
	}
	return nil
}

type RevokeTokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevokeTokenResponse) Reset()         { *m = RevokeTokenResponse{} }
func (m *RevokeTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RevokeTokenResponse) ProtoMessage()    {}
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{21}
}

func (m *RevokeTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevokeTokenResponse.Unmarshal(m, b)
}
func (m *RevokeTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevokeTokenResponse.Marshal(b, m, deterministic)
}
func (m *RevokeTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevokeTokenResponse.Merge(m, src)
}
func (m *RevokeTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RevokeTokenResponse.Size(m)
}
func (m *RevokeTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevokeTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevokeTokenResponse proto.InternalMessageInfo

type GetResetPasswordEmailTokenRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	CallbackUrl          string   `protobuf:"bytes,2,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResetPasswordEmailTokenRequest) Reset()         { *m = GetResetPasswordEmailTokenRequest{} }
func (m *GetResetPasswordEmailTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetResetPasswordEmailTokenRequest) ProtoMessage()    {}
func (*GetResetPasswordEmailTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{22}
}

func (m *GetResetPasswordEmailTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResetPasswordEmailTokenRequest.Unmarshal(m, b)
}
func (m *GetResetPasswordEmailTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResetPasswordEmailTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetResetPasswordEmailTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResetPasswordEmailTokenRequest.Merge(m, src)
}
func (m *GetResetPasswordEmailTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetResetPasswordEmailTokenRequest.Size(m)
}
func (m *GetResetPasswordEmailTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResetPasswordEmailTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetResetPasswordEmailTokenRequest proto.InternalMessageInfo

func (m *GetResetPasswordEmailTokenRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetResetPasswordEmailTokenRequest) GetCallbackUrl() string {
	if m != nil {
		return m.CallbackUrl
	}
	return ""
}

type GetResetPasswordEmailTokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResetPasswordEmailTokenResponse) Reset()         { *m = GetResetPasswordEmailTokenResponse{} }
func (m *GetResetPasswordEmailTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetResetPasswordEmailTokenResponse) ProtoMessage()    {}
func (*GetResetPasswordEmailTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{23}
}

func (m *GetResetPasswordEmailTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResetPasswordEmailTokenResponse.Unmarshal(m, b)
}
func (m *GetResetPasswordEmailTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResetPasswordEmailTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetResetPasswordEmailTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResetPasswordEmailTokenResponse.Merge(m, src)
}
func (m *GetResetPasswordEmailTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetResetPasswordEmailTokenResponse.Size(m)
}
func (m *GetResetPasswordEmailTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResetPasswordEmailTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResetPasswordEmailTokenResponse proto.InternalMessageInfo

type SetPasswordRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	OldPassword          string   `protobuf:"bytes,3,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,4,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPasswordRequest) Reset()         { *m = SetPasswordRequest{} }
func (m *SetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*SetPasswordRequest) ProtoMessage()    {}
func (*SetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{24}
}

func (m *SetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPasswordRequest.Unmarshal(m, b)
}
func (m *SetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *SetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPasswordRequest.Merge(m, src)
}
func (m *SetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_SetPasswordRequest.Size(m)
}
func (m *SetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPasswordRequest proto.InternalMessageInfo

func (m *SetPasswordRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *SetPasswordRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SetPasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *SetPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type SetPasswordResponse struct {
	AlreadyUsed          bool     `protobuf:"varint,1,opt,name=already_used,json=alreadyUsed,proto3" json:"already_used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPasswordResponse) Reset()         { *m = SetPasswordResponse{} }
func (m *SetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*SetPasswordResponse) ProtoMessage()    {}
func (*SetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{25}
}

func (m *SetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPasswordResponse.Unmarshal(m, b)
}
func (m *SetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPasswordResponse.Marshal(b, m, deterministic)
}
func (m *SetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPasswordResponse.Merge(m, src)
}
func (m *SetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_SetPasswordResponse.Size(m)
}
func (m *SetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetPasswordResponse proto.InternalMessageInfo

func (m *SetPasswordResponse) GetAlreadyUsed() bool {
	if m != nil {
		return m.AlreadyUsed
	}
	return false
}

type GetAuthorizationCodeRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Scope                []string `protobuf:"bytes,2,rep,name=scope,proto3" json:"scope,omitempty"`
	CodeVerifier         string   `protobuf:"bytes,3,opt,name=code_verifier,json=codeVerifier,proto3" json:"code_verifier,omitempty"`
	CodeVerifierMethod   string   `protobuf:"bytes,4,opt,name=code_verifier_method,json=codeVerifierMethod,proto3" json:"code_verifier_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthorizationCodeRequest) Reset()         { *m = GetAuthorizationCodeRequest{} }
func (m *GetAuthorizationCodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetAuthorizationCodeRequest) ProtoMessage()    {}
func (*GetAuthorizationCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{26}
}

func (m *GetAuthorizationCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorizationCodeRequest.Unmarshal(m, b)
}
func (m *GetAuthorizationCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorizationCodeRequest.Marshal(b, m, deterministic)
}
func (m *GetAuthorizationCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorizationCodeRequest.Merge(m, src)
}
func (m *GetAuthorizationCodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetAuthorizationCodeRequest.Size(m)
}
func (m *GetAuthorizationCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorizationCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorizationCodeRequest proto.InternalMessageInfo

func (m *GetAuthorizationCodeRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *GetAuthorizationCodeRequest) GetScope() []string {
	if m != nil {
		return m.Scope
	}
	return nil
}

func (m *GetAuthorizationCodeRequest) GetCodeVerifier() string {
	if m != nil {
		return m.CodeVerifier
	}
	return ""
}

func (m *GetAuthorizationCodeRequest) GetCodeVerifierMethod() string {
	if m != nil {
		return m.CodeVerifierMethod
	}
	return ""
}

type GetAuthorizationCodeResponse struct {
	CodeChallenge        string   `protobuf:"bytes,1,opt,name=code_challenge,json=codeChallenge,proto3" json:"code_challenge,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthorizationCodeResponse) Reset()         { *m = GetAuthorizationCodeResponse{} }
func (m *GetAuthorizationCodeResponse) String() string { return proto.CompactTextString(m) }
func (*GetAuthorizationCodeResponse) ProtoMessage()    {}
func (*GetAuthorizationCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{27}
}

func (m *GetAuthorizationCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorizationCodeResponse.Unmarshal(m, b)
}
func (m *GetAuthorizationCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorizationCodeResponse.Marshal(b, m, deterministic)
}
func (m *GetAuthorizationCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorizationCodeResponse.Merge(m, src)
}
func (m *GetAuthorizationCodeResponse) XXX_Size() int {
	return xxx_messageInfo_GetAuthorizationCodeResponse.Size(m)
}
func (m *GetAuthorizationCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorizationCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorizationCodeResponse proto.InternalMessageInfo

func (m *GetAuthorizationCodeResponse) GetCodeChallenge() string {
	if m != nil {
		return m.CodeChallenge
	}
	return ""
}

type GetOAuthAccessTokenRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Code                 []byte   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	CodeVerifier         string   `protobuf:"bytes,4,opt,name=code_verifier,json=codeVerifier,proto3" json:"code_verifier,omitempty"`
	Scope                []string `protobuf:"bytes,5,rep,name=scope,proto3" json:"scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOAuthAccessTokenRequest) Reset()         { *m = GetOAuthAccessTokenRequest{} }
func (m *GetOAuthAccessTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetOAuthAccessTokenRequest) ProtoMessage()    {}
func (*GetOAuthAccessTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{28}
}

func (m *GetOAuthAccessTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOAuthAccessTokenRequest.Unmarshal(m, b)
}
func (m *GetOAuthAccessTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOAuthAccessTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetOAuthAccessTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOAuthAccessTokenRequest.Merge(m, src)
}
func (m *GetOAuthAccessTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetOAuthAccessTokenRequest.Size(m)
}
func (m *GetOAuthAccessTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOAuthAccessTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOAuthAccessTokenRequest proto.InternalMessageInfo

func (m *GetOAuthAccessTokenRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *GetOAuthAccessTokenRequest) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *GetOAuthAccessTokenRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *GetOAuthAccessTokenRequest) GetCodeVerifier() string {
	if m != nil {
		return m.CodeVerifier
	}
	return ""
}

func (m *GetOAuthAccessTokenRequest) GetScope() []string {
	if m != nil {
		return m.Scope
	}
	return nil
}

type GetOAuthAccessTokenResponse struct {
	Jwt                  *JWT     `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOAuthAccessTokenResponse) Reset()         { *m = GetOAuthAccessTokenResponse{} }
func (m *GetOAuthAccessTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetOAuthAccessTokenResponse) ProtoMessage()    {}
func (*GetOAuthAccessTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{29}
}

func (m *GetOAuthAccessTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOAuthAccessTokenResponse.Unmarshal(m, b)
}
func (m *GetOAuthAccessTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOAuthAccessTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetOAuthAccessTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOAuthAccessTokenResponse.Merge(m, src)
}
func (m *GetOAuthAccessTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetOAuthAccessTokenResponse.Size(m)
}
func (m *GetOAuthAccessTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOAuthAccessTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOAuthAccessTokenResponse proto.InternalMessageInfo

func (m *GetOAuthAccessTokenResponse) GetJwt() *JWT {
	if m != nil {
		return m.Jwt
	}
	return nil
}

func init() {
	proto.RegisterEnum("authpb.JWTPurpose", JWTPurpose_name, JWTPurpose_value)
	proto.RegisterEnum("authpb.JWTState", JWTState_name, JWTState_value)
	proto.RegisterEnum("authpb.EventAction", EventAction_name, EventAction_value)
	proto.RegisterType((*JWTHeader)(nil), "authpb.JWTHeader")
	proto.RegisterType((*Claims)(nil), "authpb.Claims")
	proto.RegisterType((*JWT)(nil), "authpb.JWT")
	proto.RegisterType((*Credentials)(nil), "authpb.Credentials")
	proto.RegisterType((*JwtInfo)(nil), "authpb.JwtInfo")
	proto.RegisterType((*JwtEvent)(nil), "authpb.JwtEvent")
	proto.RegisterType((*FeedResponse)(nil), "authpb.FeedResponse")
	proto.RegisterType((*FindJWTRequest)(nil), "authpb.FindJWTRequest")
	proto.RegisterType((*FindJWTResponse)(nil), "authpb.FindJWTResponse")
	proto.RegisterType((*DeleteJWTRequest)(nil), "authpb.DeleteJWTRequest")
	proto.RegisterType((*DeleteJWTResponse)(nil), "authpb.DeleteJWTResponse")
	proto.RegisterType((*ListenRequest)(nil), "authpb.ListenRequest")
	proto.RegisterType((*CreateCredentialsRequest)(nil), "authpb.CreateCredentialsRequest")
	proto.RegisterType((*CreateCredentialsResponse)(nil), "authpb.CreateCredentialsResponse")
	proto.RegisterType((*AuthenticateRequest)(nil), "authpb.AuthenticateRequest")
	proto.RegisterType((*GetTokenResponse)(nil), "authpb.GetTokenResponse")
	proto.RegisterType((*ValidateEmailRequest)(nil), "authpb.ValidateEmailRequest")
	proto.RegisterType((*ValidateEmailResponse)(nil), "authpb.ValidateEmailResponse")
	proto.RegisterType((*TriggerEmailValidationRequest)(nil), "authpb.TriggerEmailValidationRequest")
	proto.RegisterType((*TriggerEmailValidationResponse)(nil), "authpb.TriggerEmailValidationResponse")
	proto.RegisterType((*RevokeTokenRequest)(nil), "authpb.RevokeTokenRequest")
	proto.RegisterType((*RevokeTokenResponse)(nil), "authpb.RevokeTokenResponse")
	proto.RegisterType((*GetResetPasswordEmailTokenRequest)(nil), "authpb.GetResetPasswordEmailTokenRequest")
	proto.RegisterType((*GetResetPasswordEmailTokenResponse)(nil), "authpb.GetResetPasswordEmailTokenResponse")
	proto.RegisterType((*SetPasswordRequest)(nil), "authpb.SetPasswordRequest")
	proto.RegisterType((*SetPasswordResponse)(nil), "authpb.SetPasswordResponse")
	proto.RegisterType((*GetAuthorizationCodeRequest)(nil), "authpb.GetAuthorizationCodeRequest")
	proto.RegisterType((*GetAuthorizationCodeResponse)(nil), "authpb.GetAuthorizationCodeResponse")
	proto.RegisterType((*GetOAuthAccessTokenRequest)(nil), "authpb.GetOAuthAccessTokenRequest")
	proto.RegisterType((*GetOAuthAccessTokenResponse)(nil), "authpb.GetOAuthAccessTokenResponse")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 1477 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0x5d, 0x53, 0xdb, 0x46,
	0x17, 0x8e, 0x6c, 0x63, 0xf0, 0x31, 0x1f, 0x62, 0x21, 0x44, 0xaf, 0x21, 0x79, 0x61, 0xf3, 0x51,
	0x42, 0xa6, 0x71, 0x4a, 0x26, 0x9d, 0x4e, 0xa6, 0x17, 0x65, 0x8c, 0x20, 0x26, 0x09, 0xa4, 0xb2,
	0x81, 0xce, 0x24, 0x33, 0x9e, 0xb5, 0xb4, 0x18, 0x81, 0x90, 0x5c, 0x69, 0x65, 0x9a, 0x66, 0x7a,
	0xd3, 0xe9, 0x3f, 0x68, 0xaf, 0x7b, 0xdb, 0xdf, 0xd1, 0xdf, 0xd0, 0x8b, 0xde, 0x77, 0xfa, 0x43,
	0x3a, 0xfb, 0x65, 0xcb, 0xd8, 0xa1, 0xbd, 0xd3, 0x9e, 0x7d, 0xf4, 0x9c, 0x73, 0x9e, 0x3d, 0xda,
	0xc7, 0x06, 0x20, 0x29, 0x3b, 0x7d, 0xdc, 0x8d, 0x23, 0x16, 0xa1, 0x22, 0x7f, 0xee, 0xb6, 0x2b,
	0x2b, 0x9d, 0x28, 0xea, 0x04, 0xb4, 0x4a, 0xba, 0x7e, 0x95, 0x84, 0x61, 0xc4, 0x08, 0xf3, 0xa3,
	0x30, 0x91, 0x28, 0x5c, 0x85, 0xd2, 0xde, 0x71, 0xf3, 0x05, 0x25, 0x1e, 0x8d, 0x91, 0x09, 0x79,
	0xf6, 0xbe, 0x6b, 0x19, 0xab, 0xc6, 0x7a, 0xc9, 0xe1, 0x8f, 0x3c, 0x42, 0x82, 0x8e, 0x95, 0x93,
	0x11, 0x12, 0x74, 0xf0, 0x5f, 0x06, 0x14, 0x6b, 0x01, 0xf1, 0x2f, 0x12, 0xbe, 0xe9, 0x27, 0x89,
	0x86, 0xfb, 0x89, 0x88, 0x24, 0x69, 0x5b, 0xc3, 0x93, 0xb4, 0x2d, 0x08, 0x52, 0xcf, 0xca, 0x2b,
	0x82, 0xd4, 0xe3, 0x11, 0xfa, 0x5d, 0xd7, 0x2a, 0xac, 0x1a, 0xeb, 0x79, 0x87, 0x3f, 0xf2, 0x48,
	0xd8, 0x3e, 0xb1, 0x26, 0x64, 0x24, 0x6c, 0x9f, 0x08, 0x66, 0xc2, 0xac, 0xa2, 0x8c, 0xf8, 0x84,
	0xf1, 0xc8, 0x19, 0xf3, 0xad, 0x49, 0xc9, 0x73, 0xc6, 0x7c, 0x64, 0xc1, 0x64, 0x8f, 0xc6, 0x89,
	0x1f, 0x85, 0xd6, 0x94, 0x88, 0xea, 0x25, 0x5a, 0x84, 0x89, 0xc4, 0x8d, 0xba, 0xd4, 0x2a, 0xad,
	0xe6, 0xd7, 0x4b, 0x8e, 0x5c, 0xa0, 0x25, 0x28, 0x46, 0xb1, 0xdf, 0xf1, 0x43, 0x0b, 0x04, 0x5c,
	0xad, 0x10, 0x82, 0x82, 0x47, 0x18, 0xb1, 0xca, 0x22, 0x2a, 0x9e, 0x71, 0x0f, 0xf2, 0x7b, 0xc7,
	0x4d, 0xf4, 0x10, 0x8a, 0xa7, 0x42, 0x19, 0xd1, 0x63, 0x79, 0x73, 0xfe, 0xb1, 0xd4, 0xf4, 0x71,
	0x5f, 0x32, 0x47, 0x01, 0xd0, 0x03, 0x28, 0xba, 0x42, 0x15, 0xd1, 0x7c, 0x79, 0x73, 0x56, 0x43,
	0xa5, 0x56, 0x8e, 0xda, 0x45, 0x2b, 0x50, 0x4a, 0xfc, 0x4e, 0x48, 0x58, 0x1a, 0x53, 0xa5, 0xca,
	0x20, 0x80, 0xdf, 0x42, 0xb9, 0x16, 0x53, 0x8f, 0x86, 0xcc, 0x27, 0x41, 0x82, 0x2a, 0x30, 0x95,
	0x26, 0x34, 0x0e, 0xc9, 0x05, 0x55, 0x2a, 0xf7, 0xd7, 0xbc, 0x49, 0x7a, 0x41, 0xfc, 0x40, 0x89,
	0x2d, 0x17, 0xfc, 0x8d, 0x2e, 0x49, 0x92, 0xcb, 0x28, 0xd6, 0x9a, 0xf7, 0xd7, 0xb8, 0x03, 0x93,
	0x7b, 0x97, 0xac, 0x1e, 0x9e, 0x44, 0x5a, 0x4d, 0x63, 0xa0, 0xa6, 0x3a, 0x83, 0xdc, 0xd0, 0x19,
	0xf0, 0x73, 0xca, 0x0f, 0xce, 0xe9, 0x01, 0x4c, 0x24, 0x8c, 0x30, 0x2a, 0xce, 0x6e, 0x76, 0xd3,
	0xcc, 0xa8, 0xd1, 0xe0, 0x71, 0x47, 0x6e, 0xe3, 0x77, 0x30, 0xb5, 0x77, 0xc9, 0xec, 0x1e, 0x0d,
	0x19, 0x7a, 0x04, 0x45, 0xe2, 0xf2, 0x81, 0x13, 0xc9, 0x66, 0x37, 0x17, 0xf4, 0x4b, 0x62, 0x7b,
	0x4b, 0x6c, 0x39, 0x0a, 0x82, 0xee, 0x42, 0xc1, 0x0f, 0x4f, 0x22, 0x25, 0xe1, 0x5c, 0x9f, 0x5f,
	0x56, 0xed, 0x88, 0x4d, 0xfc, 0x39, 0x4c, 0xef, 0x50, 0xea, 0x39, 0x34, 0xe9, 0x46, 0x61, 0x22,
	0x85, 0x88, 0xe3, 0x28, 0x56, 0xdd, 0xc8, 0x85, 0xee, 0x30, 0xd7, 0xef, 0x10, 0x7f, 0x05, 0xb3,
	0x3b, 0x7e, 0xe8, 0xed, 0x1d, 0x37, 0x1d, 0xfa, 0x6d, 0x4a, 0x13, 0x36, 0x46, 0x85, 0xa1, 0xd3,
	0xc9, 0x5d, 0x3d, 0x9d, 0x4f, 0x60, 0xae, 0xcf, 0x30, 0x48, 0x7e, 0x12, 0xa5, 0xa1, 0xa7, 0x93,
	0x8b, 0x05, 0xbe, 0x07, 0xe6, 0x36, 0x0d, 0x28, 0xa3, 0xd7, 0x25, 0xc3, 0x0f, 0x61, 0x3e, 0x83,
	0x1a, 0x10, 0xba, 0x51, 0x1a, 0x32, 0x01, 0x9c, 0x71, 0xe4, 0x02, 0xcf, 0xc1, 0xcc, 0x2b, 0x3f,
	0x61, 0x34, 0x54, 0x6c, 0xf8, 0x6b, 0xb0, 0x6a, 0x31, 0x25, 0x8c, 0x66, 0xc6, 0x45, 0x67, 0x7a,
	0x06, 0x65, 0x77, 0x10, 0x55, 0xa3, 0xdb, 0xd7, 0x3d, 0xfb, 0x42, 0x16, 0x87, 0xdf, 0xc2, 0xff,
	0xc6, 0x50, 0xaa, 0xb2, 0x6e, 0x03, 0xf0, 0xc9, 0x6b, 0x31, 0x72, 0x4e, 0xe5, 0x51, 0x4e, 0x39,
	0x25, 0x1e, 0x69, 0xf2, 0x00, 0xfa, 0x3f, 0x94, 0xc5, 0xfc, 0xa9, 0xfd, 0x9c, 0xd8, 0x07, 0x11,
	0x12, 0x00, 0xfc, 0x12, 0x16, 0xb6, 0x52, 0x76, 0xca, 0x69, 0x5d, 0x3e, 0x29, 0xaa, 0x54, 0x0b,
	0x26, 0x93, 0xb4, 0x7d, 0x46, 0x5d, 0xa6, 0x84, 0xd1, 0xcb, 0xa1, 0x41, 0xce, 0x5d, 0x19, 0x64,
	0x1b, 0xcc, 0x5d, 0xca, 0x9a, 0xd1, 0x39, 0xd7, 0xa3, 0x5f, 0x60, 0xfe, 0xec, 0x92, 0xa9, 0x66,
	0xcb, 0x99, 0xc9, 0x74, 0x78, 0x9c, 0x7f, 0xe4, 0x6e, 0xe4, 0xc9, 0x33, 0x9d, 0x71, 0xc4, 0x33,
	0xde, 0x80, 0xc5, 0x23, 0x12, 0xf8, 0x1e, 0x61, 0xd4, 0xe6, 0x95, 0xea, 0xa2, 0x90, 0x9a, 0x42,
	0x59, 0x91, 0x1c, 0xba, 0x5b, 0x70, 0xf3, 0x0a, 0x56, 0xe6, 0xc5, 0xcf, 0xe0, 0x76, 0x33, 0xf6,
	0x3b, 0x1d, 0x1a, 0x8b, 0xb8, 0x02, 0xf1, 0xa1, 0x56, 0x6c, 0xfd, 0xef, 0xd4, 0xc8, 0x7c, 0xa7,
	0x78, 0x15, 0xee, 0x7c, 0xec, 0x35, 0x45, 0xfc, 0x14, 0x90, 0x43, 0x7b, 0xd1, 0x39, 0x55, 0x7d,
	0x4a, 0xb6, 0xeb, 0xdb, 0xc4, 0x37, 0x61, 0x61, 0xe8, 0x25, 0xc5, 0xf5, 0x0e, 0xd6, 0x76, 0x29,
	0x73, 0x68, 0x42, 0xd9, 0x1b, 0x25, 0xa2, 0x48, 0x3b, 0x44, 0x3d, 0xb6, 0x50, 0xb4, 0x06, 0xd3,
	0x2e, 0x09, 0x82, 0x36, 0x71, 0xcf, 0x5b, 0x69, 0xac, 0x6f, 0x9b, 0xb2, 0x8e, 0x1d, 0xc6, 0x01,
	0xbe, 0x07, 0xf8, 0x3a, 0x76, 0x55, 0xc3, 0x4f, 0x06, 0xa0, 0xc6, 0x00, 0x91, 0x11, 0x9b, 0x8f,
	0x91, 0x16, 0x9b, 0x3f, 0x7f, 0xe4, 0x6a, 0x5b, 0x83, 0xe9, 0x28, 0xf0, 0x5a, 0x57, 0xae, 0xb7,
	0x72, 0x14, 0x78, 0x9a, 0x93, 0x43, 0x42, 0x7a, 0x39, 0x80, 0x14, 0x24, 0x24, 0xa4, 0x97, 0x1a,
	0x82, 0xbf, 0x80, 0x85, 0xa1, 0x2a, 0xd4, 0xf8, 0xac, 0xc1, 0x34, 0x09, 0x62, 0x4a, 0xbc, 0xf7,
	0xad, 0x34, 0xa1, 0x9e, 0x9a, 0xf0, 0xb2, 0x8a, 0x1d, 0x26, 0xd4, 0xc3, 0xbf, 0x19, 0xb0, 0xbc,
	0x4b, 0x19, 0x1f, 0xe3, 0x28, 0xf6, 0xbf, 0x17, 0xa7, 0x55, 0x8b, 0xbc, 0xfe, 0x2c, 0x2f, 0x43,
	0xc9, 0x0d, 0x7c, 0x1a, 0xb2, 0x96, 0xaf, 0xaf, 0x83, 0x29, 0x19, 0xa8, 0x7b, 0x03, 0x4b, 0xca,
	0x65, 0x2d, 0xe9, 0x2e, 0xcc, 0xf0, 0x49, 0x6c, 0xf5, 0x68, 0xec, 0x9f, 0xf8, 0x34, 0x56, 0x3d,
	0x4d, 0xf3, 0xe0, 0x91, 0x8a, 0xa1, 0x27, 0xb0, 0x38, 0x04, 0x6a, 0x5d, 0x50, 0x76, 0x1a, 0xe9,
	0xe6, 0x50, 0x16, 0xfb, 0x5a, 0xec, 0x60, 0x1b, 0x56, 0xc6, 0x17, 0xaa, 0x9a, 0xbd, 0x0f, 0xb3,
	0x82, 0xd1, 0x3d, 0x25, 0x41, 0x40, 0xc3, 0x8e, 0x36, 0x17, 0x51, 0x4c, 0x4d, 0x07, 0xf1, 0xaf,
	0x06, 0x54, 0x76, 0x29, 0x3b, 0xe0, 0x44, 0x5b, 0xae, 0x4b, 0x93, 0x64, 0x68, 0x5e, 0xae, 0xed,
	0x37, 0xfb, 0xbd, 0x4d, 0xcb, 0xef, 0x4d, 0x68, 0x20, 0xec, 0x43, 0x76, 0x29, 0x17, 0xa3, 0x1a,
	0x14, 0xc6, 0x68, 0xd0, 0x97, 0x6f, 0x22, 0x23, 0x1f, 0xfe, 0x52, 0x1c, 0xc8, 0x68, 0x7d, 0xff,
	0xe9, 0x4a, 0xd8, 0xd8, 0x01, 0xd8, 0x3b, 0x6e, 0xbe, 0x49, 0xe3, 0x6e, 0x94, 0x50, 0x84, 0x60,
	0x76, 0xeb, 0xb0, 0xf9, 0xc2, 0xde, 0x6f, 0xd6, 0x6b, 0x5b, 0xcd, 0xfa, 0xc1, 0xbe, 0x79, 0x03,
	0x2d, 0x82, 0xe9, 0xd8, 0x8d, 0x83, 0x43, 0xa7, 0x66, 0x37, 0x5a, 0x5b, 0xb5, 0x9a, 0xdd, 0x68,
	0x98, 0x06, 0x9a, 0x05, 0x38, 0xda, 0x7a, 0x55, 0xdf, 0x96, 0xa8, 0xdc, 0x06, 0x81, 0x29, 0x6d,
	0x80, 0xa8, 0x04, 0x13, 0x62, 0xcf, 0xbc, 0x81, 0x66, 0xa0, 0xb4, 0x7f, 0xd0, 0x6c, 0xc9, 0xa5,
	0x81, 0xca, 0x30, 0x69, 0x7f, 0xf3, 0xa6, 0xee, 0xd8, 0xdb, 0x66, 0x8e, 0x2f, 0x1c, 0xfb, 0xe8,
	0xe0, 0xa5, 0xbd, 0x6d, 0xe6, 0x39, 0x1f, 0x07, 0x36, 0xea, 0xbb, 0xfb, 0xf6, 0xb6, 0x59, 0x40,
	0xf3, 0x30, 0xc3, 0xd7, 0xf6, 0xce, 0x8e, 0x5d, 0x6b, 0xd6, 0x8f, 0x6c, 0x73, 0x62, 0xe3, 0x2e,
	0x94, 0x33, 0x76, 0x89, 0x00, 0x8a, 0xd2, 0x38, 0xcc, 0x1b, 0x68, 0x0a, 0x0a, 0x0d, 0xd2, 0xa3,
	0xa6, 0xb1, 0xf9, 0xa7, 0xa1, 0x0a, 0x89, 0x62, 0x8a, 0x36, 0xa1, 0xc0, 0x4d, 0x12, 0x99, 0x19,
	0x0f, 0x15, 0x14, 0x95, 0x45, 0x1d, 0xc9, 0x9a, 0xe8, 0xba, 0xf1, 0xc4, 0x40, 0x4f, 0xa1, 0x28,
	0x4d, 0x06, 0xdd, 0xd4, 0x98, 0x21, 0xd3, 0xa9, 0x8c, 0x90, 0x3d, 0x31, 0x50, 0x1b, 0x4a, 0xdc,
	0x13, 0x85, 0xf2, 0x68, 0xa9, 0xcf, 0x3d, 0x64, 0xb4, 0x95, 0x5b, 0x23, 0x71, 0x75, 0x29, 0xdc,
	0xfb, 0xf1, 0x8f, 0xbf, 0x7f, 0xce, 0xdd, 0x41, 0x2b, 0xe2, 0xd7, 0x69, 0xef, 0xb3, 0xea, 0xd9,
	0x25, 0xfb, 0x34, 0xe1, 0x1d, 0x54, 0x4f, 0xfc, 0xd0, 0xab, 0x7e, 0x38, 0x63, 0xfe, 0x0f, 0x9b,
	0xbf, 0x4f, 0x00, 0xd4, 0xb7, 0x5f, 0x37, 0x68, 0xdc, 0xf3, 0x5d, 0x8a, 0x3e, 0xc0, 0xfc, 0x88,
	0x51, 0xa1, 0xd5, 0x8c, 0xbf, 0x8d, 0xb5, 0xc5, 0xca, 0xda, 0x35, 0x08, 0x55, 0xce, 0x9a, 0x28,
	0x67, 0x19, 0x2f, 0xe9, 0x72, 0x88, 0x2b, 0xfc, 0xb7, 0xea, 0x8a, 0x57, 0x9e, 0x1b, 0x1b, 0x88,
	0xc0, 0x74, 0xd6, 0xc8, 0xd0, 0xb2, 0x66, 0x1d, 0x63, 0x6f, 0x15, 0x4b, 0x6f, 0x5e, 0xb5, 0x2b,
	0x5c, 0x11, 0x99, 0x16, 0xf1, 0x5c, 0xa6, 0xf1, 0x6a, 0x87, 0x32, 0x9e, 0xa2, 0x0d, 0xe5, 0xcc,
	0x25, 0x8e, 0x2a, 0x9a, 0x64, 0xd4, 0x0e, 0x2a, 0xcb, 0x63, 0xf7, 0x86, 0x73, 0x20, 0x94, 0xcd,
	0x11, 0x0b, 0x20, 0x3a, 0x83, 0x72, 0xe6, 0x1a, 0x1c, 0xe4, 0x18, 0xbd, 0xa1, 0x07, 0x39, 0xc6,
	0xdc, 0x9b, 0x18, 0x8b, 0x1c, 0x2b, 0xf8, 0x96, 0xce, 0xa1, 0xef, 0xde, 0x6a, 0xda, 0xf5, 0x94,
	0x64, 0x01, 0xcc, 0x0c, 0x79, 0x27, 0x5a, 0xd1, 0x8c, 0xe3, 0xec, 0xb7, 0x72, 0xfb, 0x23, 0xbb,
	0x2a, 0xe3, 0x1d, 0x91, 0xd1, 0x42, 0xfd, 0x33, 0x12, 0xee, 0x50, 0xed, 0x29, 0x30, 0xfa, 0xc5,
	0x80, 0xa5, 0xf1, 0xd6, 0x8a, 0xee, 0x6b, 0xe6, 0x6b, 0x1d, 0xbb, 0xf2, 0xe0, 0xdf, 0x60, 0xaa,
	0x92, 0x47, 0xa2, 0x92, 0xfb, 0x78, 0x75, 0x6c, 0x25, 0x7e, 0x14, 0x56, 0x99, 0x24, 0x78, 0x6e,
	0x6c, 0xb4, 0x8b, 0xe2, 0xef, 0xd6, 0xd3, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x67, 0x7b, 0x81,
	0xab, 0xa2, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JWTStoreClient is the client API for JWTStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JWTStoreClient interface {
	Feed(ctx context.Context, opts ...grpc.CallOption) (JWTStore_FeedClient, error)
	Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (JWTStore_ListenClient, error)
	FindToken(ctx context.Context, in *FindJWTRequest, opts ...grpc.CallOption) (*FindJWTResponse, error)
}

type jWTStoreClient struct {
	cc *grpc.ClientConn
}

func NewJWTStoreClient(cc *grpc.ClientConn) JWTStoreClient {
	return &jWTStoreClient{cc}
}

func (c *jWTStoreClient) Feed(ctx context.Context, opts ...grpc.CallOption) (JWTStore_FeedClient, error) {
	stream, err := c.cc.NewStream(ctx, &_JWTStore_serviceDesc.Streams[0], "/authpb.JWTStore/Feed", opts...)
	if err != nil {
		return nil, err
	}
	x := &jWTStoreFeedClient{stream}
	return x, nil
}

type JWTStore_FeedClient interface {
	Send(*JwtEvent) error
	Recv() (*FeedResponse, error)
	grpc.ClientStream
}

type jWTStoreFeedClient struct {
	grpc.ClientStream
}

func (x *jWTStoreFeedClient) Send(m *JwtEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *jWTStoreFeedClient) Recv() (*FeedResponse, error) {
	m := new(FeedResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jWTStoreClient) Listen(ctx context.Context, in *ListenRequest, opts ...grpc.CallOption) (JWTStore_ListenClient, error) {
	stream, err := c.cc.NewStream(ctx, &_JWTStore_serviceDesc.Streams[1], "/authpb.JWTStore/Listen", opts...)
	if err != nil {
		return nil, err
	}
	x := &jWTStoreListenClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type JWTStore_ListenClient interface {
	Recv() (*JwtEvent, error)
	grpc.ClientStream
}

type jWTStoreListenClient struct {
	grpc.ClientStream
}

func (x *jWTStoreListenClient) Recv() (*JwtEvent, error) {
	m := new(JwtEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *jWTStoreClient) FindToken(ctx context.Context, in *FindJWTRequest, opts ...grpc.CallOption) (*FindJWTResponse, error) {
	out := new(FindJWTResponse)
	err := c.cc.Invoke(ctx, "/authpb.JWTStore/FindToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JWTStoreServer is the server API for JWTStore service.
type JWTStoreServer interface {
	Feed(JWTStore_FeedServer) error
	Listen(*ListenRequest, JWTStore_ListenServer) error
	FindToken(context.Context, *FindJWTRequest) (*FindJWTResponse, error)
}

// UnimplementedJWTStoreServer can be embedded to have forward compatible implementations.
type UnimplementedJWTStoreServer struct {
}

func (*UnimplementedJWTStoreServer) Feed(srv JWTStore_FeedServer) error {
	return status.Errorf(codes.Unimplemented, "method Feed not implemented")
}
func (*UnimplementedJWTStoreServer) Listen(req *ListenRequest, srv JWTStore_ListenServer) error {
	return status.Errorf(codes.Unimplemented, "method Listen not implemented")
}
func (*UnimplementedJWTStoreServer) FindToken(ctx context.Context, req *FindJWTRequest) (*FindJWTResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindToken not implemented")
}

func RegisterJWTStoreServer(s *grpc.Server, srv JWTStoreServer) {
	s.RegisterService(&_JWTStore_serviceDesc, srv)
}

func _JWTStore_Feed_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(JWTStoreServer).Feed(&jWTStoreFeedServer{stream})
}

type JWTStore_FeedServer interface {
	Send(*FeedResponse) error
	Recv() (*JwtEvent, error)
	grpc.ServerStream
}

type jWTStoreFeedServer struct {
	grpc.ServerStream
}

func (x *jWTStoreFeedServer) Send(m *FeedResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *jWTStoreFeedServer) Recv() (*JwtEvent, error) {
	m := new(JwtEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _JWTStore_Listen_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListenRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JWTStoreServer).Listen(m, &jWTStoreListenServer{stream})
}

type JWTStore_ListenServer interface {
	Send(*JwtEvent) error
	grpc.ServerStream
}

type jWTStoreListenServer struct {
	grpc.ServerStream
}

func (x *jWTStoreListenServer) Send(m *JwtEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _JWTStore_FindToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindJWTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JWTStoreServer).FindToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.JWTStore/FindToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JWTStoreServer).FindToken(ctx, req.(*FindJWTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JWTStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authpb.JWTStore",
	HandlerType: (*JWTStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindToken",
			Handler:    _JWTStore_FindToken_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Feed",
			Handler:       _JWTStore_Feed_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Listen",
			Handler:       _JWTStore_Listen_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "auth.proto",
}

// IDMServiceClient is the client API for IDMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IDMServiceClient interface {
	CreateCredentials(ctx context.Context, in *CreateCredentialsRequest, opts ...grpc.CallOption) (*CreateCredentialsResponse, error)
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*GetTokenResponse, error)
	RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error)
	SetPassword(ctx context.Context, in *SetPasswordRequest, opts ...grpc.CallOption) (*SetPasswordResponse, error)
	ValidateEmail(ctx context.Context, in *ValidateEmailRequest, opts ...grpc.CallOption) (*ValidateEmailResponse, error)
	TriggerEmailValidation(ctx context.Context, in *TriggerEmailValidationRequest, opts ...grpc.CallOption) (*TriggerEmailValidationResponse, error)
}

type iDMServiceClient struct {
	cc *grpc.ClientConn
}

func NewIDMServiceClient(cc *grpc.ClientConn) IDMServiceClient {
	return &iDMServiceClient{cc}
}

func (c *iDMServiceClient) CreateCredentials(ctx context.Context, in *CreateCredentialsRequest, opts ...grpc.CallOption) (*CreateCredentialsResponse, error) {
	out := new(CreateCredentialsResponse)
	err := c.cc.Invoke(ctx, "/authpb.IDMService/CreateCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iDMServiceClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	out := new(GetTokenResponse)
	err := c.cc.Invoke(ctx, "/authpb.IDMService/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iDMServiceClient) RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error) {
	out := new(RevokeTokenResponse)
	err := c.cc.Invoke(ctx, "/authpb.IDMService/RevokeToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iDMServiceClient) SetPassword(ctx context.Context, in *SetPasswordRequest, opts ...grpc.CallOption) (*SetPasswordResponse, error) {
	out := new(SetPasswordResponse)
	err := c.cc.Invoke(ctx, "/authpb.IDMService/SetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iDMServiceClient) ValidateEmail(ctx context.Context, in *ValidateEmailRequest, opts ...grpc.CallOption) (*ValidateEmailResponse, error) {
	out := new(ValidateEmailResponse)
	err := c.cc.Invoke(ctx, "/authpb.IDMService/ValidateEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iDMServiceClient) TriggerEmailValidation(ctx context.Context, in *TriggerEmailValidationRequest, opts ...grpc.CallOption) (*TriggerEmailValidationResponse, error) {
	out := new(TriggerEmailValidationResponse)
	err := c.cc.Invoke(ctx, "/authpb.IDMService/TriggerEmailValidation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IDMServiceServer is the server API for IDMService service.
type IDMServiceServer interface {
	CreateCredentials(context.Context, *CreateCredentialsRequest) (*CreateCredentialsResponse, error)
	Authenticate(context.Context, *AuthenticateRequest) (*GetTokenResponse, error)
	RevokeToken(context.Context, *RevokeTokenRequest) (*RevokeTokenResponse, error)
	SetPassword(context.Context, *SetPasswordRequest) (*SetPasswordResponse, error)
	ValidateEmail(context.Context, *ValidateEmailRequest) (*ValidateEmailResponse, error)
	TriggerEmailValidation(context.Context, *TriggerEmailValidationRequest) (*TriggerEmailValidationResponse, error)
}

// UnimplementedIDMServiceServer can be embedded to have forward compatible implementations.
type UnimplementedIDMServiceServer struct {
}

func (*UnimplementedIDMServiceServer) CreateCredentials(ctx context.Context, req *CreateCredentialsRequest) (*CreateCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCredentials not implemented")
}
func (*UnimplementedIDMServiceServer) Authenticate(ctx context.Context, req *AuthenticateRequest) (*GetTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (*UnimplementedIDMServiceServer) RevokeToken(ctx context.Context, req *RevokeTokenRequest) (*RevokeTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeToken not implemented")
}
func (*UnimplementedIDMServiceServer) SetPassword(ctx context.Context, req *SetPasswordRequest) (*SetPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPassword not implemented")
}
func (*UnimplementedIDMServiceServer) ValidateEmail(ctx context.Context, req *ValidateEmailRequest) (*ValidateEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateEmail not implemented")
}
func (*UnimplementedIDMServiceServer) TriggerEmailValidation(ctx context.Context, req *TriggerEmailValidationRequest) (*TriggerEmailValidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerEmailValidation not implemented")
}

func RegisterIDMServiceServer(s *grpc.Server, srv IDMServiceServer) {
	s.RegisterService(&_IDMService_serviceDesc, srv)
}

func _IDMService_CreateCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDMServiceServer).CreateCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.IDMService/CreateCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDMServiceServer).CreateCredentials(ctx, req.(*CreateCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IDMService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDMServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.IDMService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDMServiceServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IDMService_RevokeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDMServiceServer).RevokeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.IDMService/RevokeToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDMServiceServer).RevokeToken(ctx, req.(*RevokeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IDMService_SetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDMServiceServer).SetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.IDMService/SetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDMServiceServer).SetPassword(ctx, req.(*SetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IDMService_ValidateEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDMServiceServer).ValidateEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.IDMService/ValidateEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDMServiceServer).ValidateEmail(ctx, req.(*ValidateEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IDMService_TriggerEmailValidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerEmailValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IDMServiceServer).TriggerEmailValidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authpb.IDMService/TriggerEmailValidation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IDMServiceServer).TriggerEmailValidation(ctx, req.(*TriggerEmailValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IDMService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authpb.IDMService",
	HandlerType: (*IDMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCredentials",
			Handler:    _IDMService_CreateCredentials_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _IDMService_Authenticate_Handler,
		},
		{
			MethodName: "RevokeToken",
			Handler:    _IDMService_RevokeToken_Handler,
		},
		{
			MethodName: "SetPassword",
			Handler:    _IDMService_SetPassword_Handler,
		},
		{
			MethodName: "ValidateEmail",
			Handler:    _IDMService_ValidateEmail_Handler,
		},
		{
			MethodName: "TriggerEmailValidation",
			Handler:    _IDMService_TriggerEmailValidation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
