// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tree.proto

package treepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Action int32

const (
	Action_NO_ACTION Action = 0
	Action_CREATE    Action = 1
	Action_DELETE    Action = 2
	Action_MOVE      Action = 3
	Action_RENAME    Action = 4
	Action_WRITE     Action = 5
	Action_READ      Action = 6
	Action_GROW      Action = 7
)

var Action_name = map[int32]string{
	0: "NO_ACTION",
	1: "CREATE",
	2: "DELETE",
	3: "MOVE",
	4: "RENAME",
	5: "WRITE",
	6: "READ",
	7: "GROW",
}

var Action_value = map[string]int32{
	"NO_ACTION": 0,
	"CREATE":    1,
	"DELETE":    2,
	"MOVE":      3,
	"RENAME":    4,
	"WRITE":     5,
	"READ":      6,
	"GROW":      7,
}

func (x Action) String() string {
	return proto.EnumName(Action_name, int32(x))
}

func (Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{0}
}

type NodeType int32

const (
	NodeType_UNKNOWN   NodeType = 0
	NodeType_FILE      NodeType = 1
	NodeType_DIRECTORY NodeType = 2
)

var NodeType_name = map[int32]string{
	0: "UNKNOWN",
	1: "FILE",
	2: "DIRECTORY",
}

var NodeType_value = map[string]int32{
	"UNKNOWN":   0,
	"FILE":      1,
	"DIRECTORY": 2,
}

func (x NodeType) String() string {
	return proto.EnumName(NodeType_name, int32(x))
}

func (NodeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{1}
}

type NodeInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 NodeType `protobuf:"varint,2,opt,name=type,proto3,enum=treepb.NodeType" json:"type,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Parent               string   `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	Size                 int64    `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	CreateTime           int64    `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	EditTime             int64    `protobuf:"varint,7,opt,name=edit_time,json=editTime,proto3" json:"edit_time,omitempty"`
	AccessTime           int64    `protobuf:"varint,8,opt,name=access_time,json=accessTime,proto3" json:"access_time,omitempty"`
	Hash                 string   `protobuf:"bytes,9,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{0}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NodeInfo) GetType() NodeType {
	if m != nil {
		return m.Type
	}
	return NodeType_UNKNOWN
}

func (m *NodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeInfo) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *NodeInfo) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *NodeInfo) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *NodeInfo) GetEditTime() int64 {
	if m != nil {
		return m.EditTime
	}
	return 0
}

func (m *NodeInfo) GetAccessTime() int64 {
	if m != nil {
		return m.AccessTime
	}
	return 0
}

func (m *NodeInfo) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Event struct {
	Action               Action    `protobuf:"varint,2,opt,name=action,proto3,enum=treepb.Action" json:"action,omitempty"`
	Path                 string    `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	FileInfo             *NodeInfo `protobuf:"bytes,4,opt,name=file_info,json=fileInfo,proto3" json:"file_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetAction() Action {
	if m != nil {
		return m.Action
	}
	return Action_NO_ACTION
}

func (m *Event) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Event) GetFileInfo() *NodeInfo {
	if m != nil {
		return m.FileInfo
	}
	return nil
}

type Meta struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}
func (*Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{2}
}

func (m *Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Meta.Unmarshal(m, b)
}
func (m *Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Meta.Marshal(b, m, deterministic)
}
func (m *Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Meta.Merge(m, src)
}
func (m *Meta) XXX_Size() int {
	return xxx_messageInfo_Meta.Size(m)
}
func (m *Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Meta proto.InternalMessageInfo

func (m *Meta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Meta) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ListRequest struct {
	Dir                  string   `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	Page                 uint32   `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{3}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

func (m *ListRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

type ListResponse struct {
	List                 []*NodeInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Page                 uint32      `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageCount            uint32      `protobuf:"varint,3,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{4}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetList() []*NodeInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ListResponse) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListResponse) GetPageCount() uint32 {
	if m != nil {
		return m.PageCount
	}
	return 0
}

type CreateRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Type                 NodeType `protobuf:"varint,2,opt,name=type,proto3,enum=treepb.NodeType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{5}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *CreateRequest) GetType() NodeType {
	if m != nil {
		return m.Type
	}
	return NodeType_UNKNOWN
}

type CreateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{6}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

type GetInfoRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	WithHash             bool     `protobuf:"varint,2,opt,name=with_hash,json=withHash,proto3" json:"with_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{7}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

func (m *GetInfoRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *GetInfoRequest) GetWithHash() bool {
	if m != nil {
		return m.WithHash
	}
	return false
}

type GetInfoResponse struct {
	Info                 *NodeInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{8}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetInfo() *NodeInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type GetListStreamRequest struct {
	Dir                  string   `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetListStreamRequest) Reset()         { *m = GetListStreamRequest{} }
func (m *GetListStreamRequest) String() string { return proto.CompactTextString(m) }
func (*GetListStreamRequest) ProtoMessage()    {}
func (*GetListStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{9}
}

func (m *GetListStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetListStreamRequest.Unmarshal(m, b)
}
func (m *GetListStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetListStreamRequest.Marshal(b, m, deterministic)
}
func (m *GetListStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetListStreamRequest.Merge(m, src)
}
func (m *GetListStreamRequest) XXX_Size() int {
	return xxx_messageInfo_GetListStreamRequest.Size(m)
}
func (m *GetListStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetListStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetListStreamRequest proto.InternalMessageInfo

func (m *GetListStreamRequest) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

type GetMetaRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMetaRequest) Reset()         { *m = GetMetaRequest{} }
func (m *GetMetaRequest) String() string { return proto.CompactTextString(m) }
func (*GetMetaRequest) ProtoMessage()    {}
func (*GetMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{10}
}

func (m *GetMetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMetaRequest.Unmarshal(m, b)
}
func (m *GetMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMetaRequest.Marshal(b, m, deterministic)
}
func (m *GetMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMetaRequest.Merge(m, src)
}
func (m *GetMetaRequest) XXX_Size() int {
	return xxx_messageInfo_GetMetaRequest.Size(m)
}
func (m *GetMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMetaRequest proto.InternalMessageInfo

func (m *GetMetaRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type GetMetaResponse struct {
	Meta                 []*Meta  `protobuf:"bytes,1,rep,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMetaResponse) Reset()         { *m = GetMetaResponse{} }
func (m *GetMetaResponse) String() string { return proto.CompactTextString(m) }
func (*GetMetaResponse) ProtoMessage()    {}
func (*GetMetaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{11}
}

func (m *GetMetaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMetaResponse.Unmarshal(m, b)
}
func (m *GetMetaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMetaResponse.Marshal(b, m, deterministic)
}
func (m *GetMetaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMetaResponse.Merge(m, src)
}
func (m *GetMetaResponse) XXX_Size() int {
	return xxx_messageInfo_GetMetaResponse.Size(m)
}
func (m *GetMetaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMetaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMetaResponse proto.InternalMessageInfo

func (m *GetMetaResponse) GetMeta() []*Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type SetMetaRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetMetaRequest) Reset()         { *m = SetMetaRequest{} }
func (m *SetMetaRequest) String() string { return proto.CompactTextString(m) }
func (*SetMetaRequest) ProtoMessage()    {}
func (*SetMetaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{12}
}

func (m *SetMetaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMetaRequest.Unmarshal(m, b)
}
func (m *SetMetaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMetaRequest.Marshal(b, m, deterministic)
}
func (m *SetMetaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMetaRequest.Merge(m, src)
}
func (m *SetMetaRequest) XXX_Size() int {
	return xxx_messageInfo_SetMetaRequest.Size(m)
}
func (m *SetMetaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMetaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetMetaRequest proto.InternalMessageInfo

func (m *SetMetaRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type SetMetaResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetMetaResponse) Reset()         { *m = SetMetaResponse{} }
func (m *SetMetaResponse) String() string { return proto.CompactTextString(m) }
func (*SetMetaResponse) ProtoMessage()    {}
func (*SetMetaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{13}
}

func (m *SetMetaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetMetaResponse.Unmarshal(m, b)
}
func (m *SetMetaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetMetaResponse.Marshal(b, m, deterministic)
}
func (m *SetMetaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetMetaResponse.Merge(m, src)
}
func (m *SetMetaResponse) XXX_Size() int {
	return xxx_messageInfo_SetMetaResponse.Size(m)
}
func (m *SetMetaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetMetaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetMetaResponse proto.InternalMessageInfo

type CopyRequest struct {
	Paths                []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	Dir                  string   `protobuf:"bytes,2,opt,name=dir,proto3" json:"dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyRequest) Reset()         { *m = CopyRequest{} }
func (m *CopyRequest) String() string { return proto.CompactTextString(m) }
func (*CopyRequest) ProtoMessage()    {}
func (*CopyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{14}
}

func (m *CopyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyRequest.Unmarshal(m, b)
}
func (m *CopyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyRequest.Marshal(b, m, deterministic)
}
func (m *CopyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyRequest.Merge(m, src)
}
func (m *CopyRequest) XXX_Size() int {
	return xxx_messageInfo_CopyRequest.Size(m)
}
func (m *CopyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CopyRequest proto.InternalMessageInfo

func (m *CopyRequest) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *CopyRequest) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

type CopyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyResponse) Reset()         { *m = CopyResponse{} }
func (m *CopyResponse) String() string { return proto.CompactTextString(m) }
func (*CopyResponse) ProtoMessage()    {}
func (*CopyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{15}
}

func (m *CopyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyResponse.Unmarshal(m, b)
}
func (m *CopyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyResponse.Marshal(b, m, deterministic)
}
func (m *CopyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyResponse.Merge(m, src)
}
func (m *CopyResponse) XXX_Size() int {
	return xxx_messageInfo_CopyResponse.Size(m)
}
func (m *CopyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CopyResponse proto.InternalMessageInfo

type MoveRequest struct {
	Paths                []string `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	DestinationFolder    string   `protobuf:"bytes,2,opt,name=destination_folder,json=destinationFolder,proto3" json:"destination_folder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveRequest) Reset()         { *m = MoveRequest{} }
func (m *MoveRequest) String() string { return proto.CompactTextString(m) }
func (*MoveRequest) ProtoMessage()    {}
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{16}
}

func (m *MoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveRequest.Unmarshal(m, b)
}
func (m *MoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveRequest.Marshal(b, m, deterministic)
}
func (m *MoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveRequest.Merge(m, src)
}
func (m *MoveRequest) XXX_Size() int {
	return xxx_messageInfo_MoveRequest.Size(m)
}
func (m *MoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MoveRequest proto.InternalMessageInfo

func (m *MoveRequest) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

func (m *MoveRequest) GetDestinationFolder() string {
	if m != nil {
		return m.DestinationFolder
	}
	return ""
}

type MoveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveResponse) Reset()         { *m = MoveResponse{} }
func (m *MoveResponse) String() string { return proto.CompactTextString(m) }
func (*MoveResponse) ProtoMessage()    {}
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{17}
}

func (m *MoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveResponse.Unmarshal(m, b)
}
func (m *MoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveResponse.Marshal(b, m, deterministic)
}
func (m *MoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveResponse.Merge(m, src)
}
func (m *MoveResponse) XXX_Size() int {
	return xxx_messageInfo_MoveResponse.Size(m)
}
func (m *MoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MoveResponse proto.InternalMessageInfo

type RenameRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	NewName              string   `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameRequest) Reset()         { *m = RenameRequest{} }
func (m *RenameRequest) String() string { return proto.CompactTextString(m) }
func (*RenameRequest) ProtoMessage()    {}
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{18}
}

func (m *RenameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameRequest.Unmarshal(m, b)
}
func (m *RenameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameRequest.Marshal(b, m, deterministic)
}
func (m *RenameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameRequest.Merge(m, src)
}
func (m *RenameRequest) XXX_Size() int {
	return xxx_messageInfo_RenameRequest.Size(m)
}
func (m *RenameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RenameRequest proto.InternalMessageInfo

func (m *RenameRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RenameRequest) GetNewName() string {
	if m != nil {
		return m.NewName
	}
	return ""
}

type RenameResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RenameResponse) Reset()         { *m = RenameResponse{} }
func (m *RenameResponse) String() string { return proto.CompactTextString(m) }
func (*RenameResponse) ProtoMessage()    {}
func (*RenameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{19}
}

func (m *RenameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RenameResponse.Unmarshal(m, b)
}
func (m *RenameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RenameResponse.Marshal(b, m, deterministic)
}
func (m *RenameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RenameResponse.Merge(m, src)
}
func (m *RenameResponse) XXX_Size() int {
	return xxx_messageInfo_RenameResponse.Size(m)
}
func (m *RenameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RenameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RenameResponse proto.InternalMessageInfo

type UploadInfoRequest struct {
	File                 string   `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	ContentSize          int64    `protobuf:"varint,2,opt,name=content_size,json=contentSize,proto3" json:"content_size,omitempty"`
	Append               bool     `protobuf:"varint,3,opt,name=append,proto3" json:"append,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadInfoRequest) Reset()         { *m = UploadInfoRequest{} }
func (m *UploadInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UploadInfoRequest) ProtoMessage()    {}
func (*UploadInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{20}
}

func (m *UploadInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadInfoRequest.Unmarshal(m, b)
}
func (m *UploadInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadInfoRequest.Marshal(b, m, deterministic)
}
func (m *UploadInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadInfoRequest.Merge(m, src)
}
func (m *UploadInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UploadInfoRequest.Size(m)
}
func (m *UploadInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadInfoRequest proto.InternalMessageInfo

func (m *UploadInfoRequest) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *UploadInfoRequest) GetContentSize() int64 {
	if m != nil {
		return m.ContentSize
	}
	return 0
}

func (m *UploadInfoRequest) GetAppend() bool {
	if m != nil {
		return m.Append
	}
	return false
}

type UploadInfoResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadInfoResponse) Reset()         { *m = UploadInfoResponse{} }
func (m *UploadInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UploadInfoResponse) ProtoMessage()    {}
func (*UploadInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{21}
}

func (m *UploadInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadInfoResponse.Unmarshal(m, b)
}
func (m *UploadInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadInfoResponse.Marshal(b, m, deterministic)
}
func (m *UploadInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadInfoResponse.Merge(m, src)
}
func (m *UploadInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UploadInfoResponse.Size(m)
}
func (m *UploadInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadInfoResponse proto.InternalMessageInfo

func (m *UploadInfoResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type DownloadInfoRequest struct {
	File                 string   `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadInfoRequest) Reset()         { *m = DownloadInfoRequest{} }
func (m *DownloadInfoRequest) String() string { return proto.CompactTextString(m) }
func (*DownloadInfoRequest) ProtoMessage()    {}
func (*DownloadInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{22}
}

func (m *DownloadInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadInfoRequest.Unmarshal(m, b)
}
func (m *DownloadInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadInfoRequest.Marshal(b, m, deterministic)
}
func (m *DownloadInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadInfoRequest.Merge(m, src)
}
func (m *DownloadInfoRequest) XXX_Size() int {
	return xxx_messageInfo_DownloadInfoRequest.Size(m)
}
func (m *DownloadInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadInfoRequest proto.InternalMessageInfo

func (m *DownloadInfoRequest) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

type DownloadInfoResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadInfoResponse) Reset()         { *m = DownloadInfoResponse{} }
func (m *DownloadInfoResponse) String() string { return proto.CompactTextString(m) }
func (*DownloadInfoResponse) ProtoMessage()    {}
func (*DownloadInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{23}
}

func (m *DownloadInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadInfoResponse.Unmarshal(m, b)
}
func (m *DownloadInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadInfoResponse.Marshal(b, m, deterministic)
}
func (m *DownloadInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadInfoResponse.Merge(m, src)
}
func (m *DownloadInfoResponse) XXX_Size() int {
	return xxx_messageInfo_DownloadInfoResponse.Size(m)
}
func (m *DownloadInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadInfoResponse proto.InternalMessageInfo

func (m *DownloadInfoResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type DeleteRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{24}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type DeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb3889276909882a, []int{25}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("treepb.Action", Action_name, Action_value)
	proto.RegisterEnum("treepb.NodeType", NodeType_name, NodeType_value)
	proto.RegisterType((*NodeInfo)(nil), "treepb.NodeInfo")
	proto.RegisterType((*Event)(nil), "treepb.Event")
	proto.RegisterType((*Meta)(nil), "treepb.Meta")
	proto.RegisterType((*ListRequest)(nil), "treepb.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "treepb.ListResponse")
	proto.RegisterType((*CreateRequest)(nil), "treepb.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "treepb.CreateResponse")
	proto.RegisterType((*GetInfoRequest)(nil), "treepb.GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "treepb.GetInfoResponse")
	proto.RegisterType((*GetListStreamRequest)(nil), "treepb.GetListStreamRequest")
	proto.RegisterType((*GetMetaRequest)(nil), "treepb.GetMetaRequest")
	proto.RegisterType((*GetMetaResponse)(nil), "treepb.GetMetaResponse")
	proto.RegisterType((*SetMetaRequest)(nil), "treepb.SetMetaRequest")
	proto.RegisterType((*SetMetaResponse)(nil), "treepb.SetMetaResponse")
	proto.RegisterType((*CopyRequest)(nil), "treepb.CopyRequest")
	proto.RegisterType((*CopyResponse)(nil), "treepb.CopyResponse")
	proto.RegisterType((*MoveRequest)(nil), "treepb.MoveRequest")
	proto.RegisterType((*MoveResponse)(nil), "treepb.MoveResponse")
	proto.RegisterType((*RenameRequest)(nil), "treepb.RenameRequest")
	proto.RegisterType((*RenameResponse)(nil), "treepb.RenameResponse")
	proto.RegisterType((*UploadInfoRequest)(nil), "treepb.UploadInfoRequest")
	proto.RegisterType((*UploadInfoResponse)(nil), "treepb.UploadInfoResponse")
	proto.RegisterType((*DownloadInfoRequest)(nil), "treepb.DownloadInfoRequest")
	proto.RegisterType((*DownloadInfoResponse)(nil), "treepb.DownloadInfoResponse")
	proto.RegisterType((*DeleteRequest)(nil), "treepb.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "treepb.DeleteResponse")
}

func init() { proto.RegisterFile("tree.proto", fileDescriptor_cb3889276909882a) }

var fileDescriptor_cb3889276909882a = []byte{
	// 1152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xff, 0x4e, 0xe3, 0xc6,
	0x13, 0xff, 0x3a, 0x71, 0x7e, 0x4d, 0x48, 0xce, 0xec, 0xf1, 0xe5, 0x72, 0x39, 0xae, 0xa4, 0xbe,
	0x13, 0x4a, 0x91, 0x8e, 0xd0, 0x43, 0x55, 0xa5, 0xfe, 0x71, 0x52, 0x14, 0x7c, 0x34, 0x2a, 0x24,
	0xd2, 0x26, 0x14, 0x55, 0x57, 0x29, 0x32, 0xf1, 0x02, 0xae, 0x12, 0xdb, 0xb5, 0x37, 0x41, 0x14,
	0xf1, 0x4f, 0x5f, 0xa1, 0xcf, 0xd3, 0xa7, 0xe8, 0x2b, 0xf4, 0x0d, 0xfa, 0x02, 0xd5, 0xec, 0x7a,
	0x89, 0x0d, 0x09, 0xbd, 0xbf, 0x98, 0xcc, 0xcc, 0x7e, 0xe6, 0xb3, 0x33, 0x3b, 0x1f, 0x03, 0xc0,
	0x43, 0xc6, 0xf6, 0x82, 0xd0, 0xe7, 0x3e, 0xc9, 0xa3, 0x1d, 0x9c, 0xd7, 0xb7, 0x2e, 0x7d, 0xff,
	0x72, 0xc2, 0x5a, 0x76, 0xe0, 0xb6, 0x6c, 0xcf, 0xf3, 0xb9, 0xcd, 0x5d, 0xdf, 0x8b, 0x64, 0x96,
	0xf9, 0x8f, 0x06, 0xc5, 0x9e, 0xef, 0xb0, 0xae, 0x77, 0xe1, 0x93, 0x2a, 0x64, 0x5c, 0xa7, 0xa6,
	0x35, 0xb4, 0x66, 0x96, 0x66, 0x5c, 0x87, 0xbc, 0x05, 0x9d, 0xdf, 0x04, 0xac, 0x96, 0x69, 0x68,
	0xcd, 0xea, 0x7b, 0x63, 0x4f, 0x22, 0xee, 0x61, 0xfe, 0xf0, 0x26, 0x60, 0x54, 0x44, 0x09, 0x01,
	0xdd, 0xb3, 0xa7, 0xac, 0x96, 0x6d, 0x68, 0xcd, 0x12, 0x15, 0x36, 0xd9, 0x84, 0x7c, 0x60, 0x87,
	0xcc, 0xe3, 0x35, 0x5d, 0x78, 0xe3, 0x5f, 0x98, 0x1b, 0xb9, 0xbf, 0xb1, 0x5a, 0x4e, 0xd4, 0x10,
	0x36, 0xd9, 0x86, 0xf2, 0x38, 0x64, 0x36, 0x67, 0x23, 0xee, 0x4e, 0x59, 0x2d, 0x2f, 0x42, 0x20,
	0x5d, 0x43, 0x77, 0xca, 0xc8, 0x2b, 0x28, 0x31, 0xc7, 0xe5, 0x32, 0x5c, 0x10, 0xe1, 0x22, 0x3a,
	0x44, 0x70, 0x1b, 0xca, 0xf6, 0x78, 0xcc, 0xa2, 0x48, 0x86, 0x8b, 0xf2, 0xb4, 0x74, 0x89, 0x04,
	0x02, 0xfa, 0x95, 0x1d, 0x5d, 0xd5, 0x4a, 0x92, 0x1e, 0xda, 0x66, 0x08, 0x39, 0x6b, 0x8e, 0x7c,
	0x76, 0x20, 0x6f, 0x8f, 0xb1, 0x1f, 0xf1, 0x1d, 0xab, 0xea, 0x8e, 0x6d, 0xe1, 0xa5, 0x71, 0x14,
	0x41, 0x02, 0x9b, 0x5f, 0xa9, 0x3b, 0xa2, 0x4d, 0xde, 0x41, 0xe9, 0xc2, 0x9d, 0xb0, 0x91, 0xeb,
	0x5d, 0xf8, 0xe2, 0x9a, 0xe5, 0x74, 0x8b, 0xb0, 0xa5, 0xb4, 0x88, 0x29, 0x68, 0x99, 0xfb, 0xa0,
	0x9f, 0x30, 0x6e, 0xdf, 0xb7, 0x4b, 0x4b, 0xb4, 0x6b, 0x03, 0x72, 0x73, 0x7b, 0x32, 0x53, 0x3d,
	0x94, 0x3f, 0xcc, 0x03, 0x28, 0x1f, 0xbb, 0x11, 0xa7, 0xec, 0xd7, 0x19, 0x8b, 0x38, 0x31, 0x20,
	0xeb, 0xb8, 0x61, 0x7c, 0x0e, 0x4d, 0xc9, 0xea, 0x52, 0xce, 0xa7, 0x42, 0x85, 0x6d, 0x5e, 0xc2,
	0x9a, 0x3c, 0x14, 0x05, 0xbe, 0x17, 0x31, 0x9c, 0xe1, 0xc4, 0x8d, 0x78, 0x4d, 0x6b, 0x64, 0x97,
	0x12, 0x14, 0xd1, 0x65, 0x48, 0xe4, 0x35, 0x00, 0xfe, 0x1d, 0x8d, 0xfd, 0x99, 0xc7, 0x05, 0xb3,
	0x0a, 0x2d, 0xa1, 0xa7, 0x83, 0x0e, 0xb3, 0x0b, 0x95, 0x8e, 0x98, 0x91, 0xe2, 0xa7, 0x7a, 0xa4,
	0x25, 0x7a, 0xf4, 0x59, 0x2f, 0xc8, 0x34, 0xa0, 0xaa, 0xa0, 0x24, 0x6b, 0xb3, 0x0d, 0xd5, 0x23,
	0xc6, 0x05, 0xc1, 0x27, 0xd0, 0x5f, 0x41, 0xe9, 0xda, 0xe5, 0x57, 0x23, 0x31, 0x5f, 0x2c, 0x51,
	0xa4, 0x45, 0x74, 0x7c, 0x8f, 0x33, 0xfe, 0x16, 0x9e, 0xdd, 0x43, 0x2c, 0x7a, 0x21, 0x86, 0xa5,
	0xad, 0x18, 0x96, 0x88, 0x9a, 0x4d, 0xd8, 0x38, 0x62, 0x1c, 0x9b, 0x38, 0xe0, 0x21, 0xb3, 0xa7,
	0x2b, 0xfb, 0x6f, 0xbe, 0x15, 0x2c, 0x71, 0xaa, 0x4f, 0xb0, 0x34, 0x0f, 0x04, 0x11, 0x99, 0x15,
	0x13, 0x69, 0x80, 0x3e, 0x65, 0xdc, 0x8e, 0x87, 0xb2, 0xa6, 0x88, 0x88, 0x1c, 0x11, 0x41, 0xe8,
	0xc1, 0x7f, 0x43, 0xaf, 0xc3, 0xb3, 0x41, 0x1a, 0xda, 0xfc, 0x06, 0xca, 0x1d, 0x3f, 0xb8, 0x51,
	0xa7, 0x36, 0x20, 0x87, 0x99, 0x91, 0x28, 0x55, 0xa2, 0xf2, 0x87, 0xba, 0x4a, 0x66, 0x71, 0x95,
	0x2a, 0xac, 0xc9, 0x63, 0x31, 0x0c, 0x85, 0xf2, 0x89, 0x3f, 0x67, 0x4f, 0xc3, 0xbc, 0x03, 0xe2,
	0xb0, 0x88, 0xbb, 0x9e, 0x90, 0x94, 0xd1, 0x85, 0x3f, 0x71, 0x98, 0x42, 0x5d, 0x4f, 0x44, 0x3e,
	0x8a, 0x00, 0xd6, 0x90, 0x98, 0x71, 0x8d, 0x0f, 0x50, 0xa1, 0x0c, 0xdf, 0xff, 0x53, 0x33, 0x7e,
	0x09, 0x45, 0x8f, 0x5d, 0x8f, 0xc4, 0xca, 0x48, 0xe4, 0x82, 0xc7, 0xae, 0x7b, 0xf6, 0x54, 0x3c,
	0x1b, 0x75, 0x3e, 0x46, 0x3c, 0x87, 0xf5, 0xd3, 0x60, 0xe2, 0xdb, 0xce, 0x83, 0x97, 0x83, 0x4b,
	0xa8, 0x50, 0xd1, 0x26, 0x5f, 0xc2, 0xda, 0xd8, 0xf7, 0x38, 0xf3, 0xf8, 0x48, 0xe8, 0x51, 0x46,
	0xc8, 0x46, 0x39, 0xf6, 0x0d, 0x50, 0x96, 0x36, 0x21, 0x6f, 0x07, 0x01, 0xf3, 0x1c, 0xf1, 0xf4,
	0x8b, 0x34, 0xfe, 0x65, 0xee, 0x00, 0x49, 0xd6, 0x88, 0x27, 0x6a, 0x40, 0x76, 0x16, 0x4e, 0xd4,
	0xe3, 0x98, 0x85, 0x13, 0xf3, 0x2b, 0x78, 0x7e, 0xe8, 0x5f, 0x7b, 0x9f, 0xc1, 0x06, 0x5f, 0x5c,
	0x3a, 0x75, 0x25, 0xe8, 0x1b, 0xa8, 0x1c, 0xb2, 0x09, 0x7b, 0x72, 0xe9, 0xb0, 0x2f, 0x2a, 0x49,
	0x02, 0xed, 0x3a, 0x90, 0x97, 0x82, 0x46, 0x2a, 0x50, 0xea, 0xf5, 0x47, 0xed, 0xce, 0xb0, 0xdb,
	0xef, 0x19, 0xff, 0x23, 0x00, 0xf9, 0x0e, 0xb5, 0xda, 0x43, 0xcb, 0xd0, 0xd0, 0x3e, 0xb4, 0x8e,
	0xad, 0xa1, 0x65, 0x64, 0x48, 0x11, 0xf4, 0x93, 0xfe, 0x8f, 0x96, 0x91, 0x45, 0x2f, 0xb5, 0x7a,
	0xed, 0x13, 0xcb, 0xd0, 0x49, 0x09, 0x72, 0x67, 0xb4, 0x3b, 0xb4, 0x8c, 0x1c, 0x26, 0x50, 0xab,
	0x7d, 0x68, 0xe4, 0xd1, 0x3a, 0xa2, 0xfd, 0x33, 0xa3, 0xb0, 0xbb, 0x2f, 0x3f, 0x25, 0xb8, 0xd8,
	0xa4, 0x0c, 0x85, 0xd3, 0xde, 0x0f, 0xbd, 0xfe, 0x19, 0x56, 0x29, 0x82, 0xfe, 0xb1, 0x7b, 0x8c,
	0x35, 0x2a, 0x50, 0x3a, 0xec, 0x52, 0xab, 0x33, 0xec, 0xd3, 0x9f, 0x8c, 0xcc, 0xfb, 0x3f, 0x8b,
	0x50, 0x1e, 0x86, 0x8c, 0x0d, 0x58, 0x38, 0x77, 0xc7, 0x8c, 0x50, 0xd0, 0x71, 0xef, 0xc8, 0x73,
	0xb5, 0x11, 0x09, 0xfd, 0xab, 0x6f, 0xa4, 0x9d, 0xf1, 0xc8, 0xb7, 0x7f, 0xff, 0xeb, 0xef, 0x3f,
	0x32, 0x2f, 0xc9, 0x0b, 0xf1, 0x81, 0x9b, 0x7f, 0xdd, 0xc2, 0xa4, 0x16, 0x8a, 0x5a, 0xeb, 0xd6,
	0x71, 0xc3, 0x3b, 0xd2, 0x86, 0x4a, 0x6a, 0x9d, 0xc9, 0x96, 0xc2, 0x59, 0xb6, 0xe5, 0xf5, 0x47,
	0xaa, 0xb0, 0xaf, 0x91, 0x4f, 0x90, 0x97, 0xfa, 0x44, 0xfe, 0xaf, 0xa2, 0x29, 0xe9, 0xab, 0x6f,
	0x3e, 0x74, 0xc7, 0xe4, 0x4c, 0x41, 0x6e, 0x8b, 0xd4, 0x53, 0xe4, 0xe4, 0xa7, 0xad, 0x75, 0x8b,
	0xc3, 0xba, 0x23, 0x3f, 0x43, 0x21, 0xd6, 0x29, 0xb2, 0x99, 0x60, 0x96, 0x78, 0x33, 0xf5, 0x17,
	0x8f, 0xfc, 0x31, 0x7e, 0x43, 0xe0, 0xd7, 0x49, 0x2d, 0x85, 0x8f, 0x2a, 0xa6, 0xd0, 0x3f, 0xdc,
	0x0b, 0xe9, 0x80, 0x45, 0x11, 0xbe, 0x80, 0x55, 0x45, 0x1e, 0x5d, 0xbc, 0xa9, 0xed, 0x6b, 0x31,
	0x3b, 0xf1, 0xe1, 0x4a, 0x1e, 0x4c, 0x08, 0x53, 0x8a, 0x5d, 0x4a, 0x8a, 0x96, 0xb3, 0x43, 0x79,
	0x53, 0xec, 0x46, 0x50, 0x18, 0x3c, 0x44, 0x1f, 0xac, 0x40, 0x7f, 0x28, 0x74, 0x6f, 0x04, 0xfa,
	0x6b, 0x73, 0x25, 0xfa, 0x77, 0xda, 0x2e, 0x09, 0xa1, 0xac, 0x36, 0xeb, 0x94, 0x1e, 0x93, 0x57,
	0x0a, 0x6c, 0xc9, 0x66, 0xd6, 0xb7, 0x96, 0x07, 0xe3, 0x72, 0x4d, 0x51, 0xce, 0x24, 0x8d, 0x54,
	0x39, 0x27, 0x4e, 0x1d, 0xcd, 0xc2, 0x49, 0xeb, 0x16, 0x97, 0xf9, 0x8e, 0xfc, 0x02, 0x25, 0x29,
	0x10, 0x58, 0xf1, 0xa5, 0x02, 0x7d, 0xa4, 0x4b, 0xf5, 0xfa, 0xb2, 0x50, 0x5c, 0x6d, 0x47, 0x54,
	0x6b, 0x90, 0x2f, 0x52, 0xd5, 0x66, 0xc1, 0xc3, 0x5a, 0x7d, 0xd0, 0x51, 0xb6, 0x17, 0x0b, 0x93,
	0xd0, 0xfe, 0xc5, 0xc2, 0xa4, 0x94, 0x7d, 0x4b, 0x40, 0x6f, 0x9a, 0xeb, 0xe9, 0x37, 0xe9, 0x07,
	0x37, 0xd8, 0xb0, 0x3e, 0xe8, 0xa8, 0xd1, 0x0b, 0xc0, 0xc4, 0x57, 0x60, 0x01, 0x98, 0x92, 0xf1,
	0xe5, 0x80, 0x53, 0x7f, 0xce, 0x10, 0xf0, 0x13, 0xe4, 0xa5, 0x18, 0x2d, 0x76, 0x27, 0xa5, 0x60,
	0x8b, 0xdd, 0x49, 0x6b, 0xd6, 0x8a, 0xdd, 0x71, 0x44, 0x52, 0x3c, 0xe1, 0xf3, 0xbc, 0xf8, 0x27,
	0xf6, 0xe0, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x2c, 0xb5, 0xc3, 0xf8, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TreeServiceClient is the client API for TreeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TreeServiceClient interface {
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	GetListStream(ctx context.Context, in *GetListStreamRequest, opts ...grpc.CallOption) (TreeService_GetListStreamClient, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	GetInfoSession(ctx context.Context, opts ...grpc.CallOption) (TreeService_GetInfoSessionClient, error)
	GetMeta(ctx context.Context, in *GetMetaRequest, opts ...grpc.CallOption) (*GetMetaResponse, error)
	SetMeta(ctx context.Context, in *SetMetaRequest, opts ...grpc.CallOption) (*SetMetaResponse, error)
	DownloadURL(ctx context.Context, in *DownloadInfoRequest, opts ...grpc.CallOption) (*DownloadInfoResponse, error)
	UploadURL(ctx context.Context, in *UploadInfoRequest, opts ...grpc.CallOption) (*UploadInfoResponse, error)
	Copy(ctx context.Context, in *CopyRequest, opts ...grpc.CallOption) (*CopyResponse, error)
	Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type treeServiceClient struct {
	cc *grpc.ClientConn
}

func NewTreeServiceClient(cc *grpc.ClientConn) TreeServiceClient {
	return &treeServiceClient{cc}
}

func (c *treeServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/treepb.TreeService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) GetListStream(ctx context.Context, in *GetListStreamRequest, opts ...grpc.CallOption) (TreeService_GetListStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TreeService_serviceDesc.Streams[0], "/treepb.TreeService/GetListStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &treeServiceGetListStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TreeService_GetListStreamClient interface {
	Recv() (*NodeInfo, error)
	grpc.ClientStream
}

type treeServiceGetListStreamClient struct {
	grpc.ClientStream
}

func (x *treeServiceGetListStreamClient) Recv() (*NodeInfo, error) {
	m := new(NodeInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *treeServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/treepb.TreeService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, "/treepb.TreeService/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) GetInfoSession(ctx context.Context, opts ...grpc.CallOption) (TreeService_GetInfoSessionClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TreeService_serviceDesc.Streams[1], "/treepb.TreeService/GetInfoSession", opts...)
	if err != nil {
		return nil, err
	}
	x := &treeServiceGetInfoSessionClient{stream}
	return x, nil
}

type TreeService_GetInfoSessionClient interface {
	Send(*GetInfoRequest) error
	Recv() (*NodeInfo, error)
	grpc.ClientStream
}

type treeServiceGetInfoSessionClient struct {
	grpc.ClientStream
}

func (x *treeServiceGetInfoSessionClient) Send(m *GetInfoRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *treeServiceGetInfoSessionClient) Recv() (*NodeInfo, error) {
	m := new(NodeInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *treeServiceClient) GetMeta(ctx context.Context, in *GetMetaRequest, opts ...grpc.CallOption) (*GetMetaResponse, error) {
	out := new(GetMetaResponse)
	err := c.cc.Invoke(ctx, "/treepb.TreeService/GetMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) SetMeta(ctx context.Context, in *SetMetaRequest, opts ...grpc.CallOption) (*SetMetaResponse, error) {
	out := new(SetMetaResponse)
	err := c.cc.Invoke(ctx, "/treepb.TreeService/SetMeta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) DownloadURL(ctx context.Context, in *DownloadInfoRequest, opts ...grpc.CallOption) (*DownloadInfoResponse, error) {
	out := new(DownloadInfoResponse)
	err := c.cc.Invoke(ctx, "/treepb.TreeService/DownloadURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) UploadURL(ctx context.Context, in *UploadInfoRequest, opts ...grpc.CallOption) (*UploadInfoResponse, error) {
	out := new(UploadInfoResponse)
	err := c.cc.Invoke(ctx, "/treepb.TreeService/UploadURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) Copy(ctx context.Context, in *CopyRequest, opts ...grpc.CallOption) (*CopyResponse, error) {
	out := new(CopyResponse)
	err := c.cc.Invoke(ctx, "/treepb.TreeService/Copy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) Move(ctx context.Context, in *MoveRequest, opts ...grpc.CallOption) (*MoveResponse, error) {
	out := new(MoveResponse)
	err := c.cc.Invoke(ctx, "/treepb.TreeService/Move", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/treepb.TreeService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TreeServiceServer is the server API for TreeService service.
type TreeServiceServer interface {
	List(context.Context, *ListRequest) (*ListResponse, error)
	GetListStream(*GetListStreamRequest, TreeService_GetListStreamServer) error
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	GetInfoSession(TreeService_GetInfoSessionServer) error
	GetMeta(context.Context, *GetMetaRequest) (*GetMetaResponse, error)
	SetMeta(context.Context, *SetMetaRequest) (*SetMetaResponse, error)
	DownloadURL(context.Context, *DownloadInfoRequest) (*DownloadInfoResponse, error)
	UploadURL(context.Context, *UploadInfoRequest) (*UploadInfoResponse, error)
	Copy(context.Context, *CopyRequest) (*CopyResponse, error)
	Move(context.Context, *MoveRequest) (*MoveResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

// UnimplementedTreeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTreeServiceServer struct {
}

func (*UnimplementedTreeServiceServer) List(ctx context.Context, req *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedTreeServiceServer) GetListStream(req *GetListStreamRequest, srv TreeService_GetListStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetListStream not implemented")
}
func (*UnimplementedTreeServiceServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedTreeServiceServer) GetInfo(ctx context.Context, req *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (*UnimplementedTreeServiceServer) GetInfoSession(srv TreeService_GetInfoSessionServer) error {
	return status.Errorf(codes.Unimplemented, "method GetInfoSession not implemented")
}
func (*UnimplementedTreeServiceServer) GetMeta(ctx context.Context, req *GetMetaRequest) (*GetMetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMeta not implemented")
}
func (*UnimplementedTreeServiceServer) SetMeta(ctx context.Context, req *SetMetaRequest) (*SetMetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMeta not implemented")
}
func (*UnimplementedTreeServiceServer) DownloadURL(ctx context.Context, req *DownloadInfoRequest) (*DownloadInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DownloadURL not implemented")
}
func (*UnimplementedTreeServiceServer) UploadURL(ctx context.Context, req *UploadInfoRequest) (*UploadInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadURL not implemented")
}
func (*UnimplementedTreeServiceServer) Copy(ctx context.Context, req *CopyRequest) (*CopyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Copy not implemented")
}
func (*UnimplementedTreeServiceServer) Move(ctx context.Context, req *MoveRequest) (*MoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Move not implemented")
}
func (*UnimplementedTreeServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterTreeServiceServer(s *grpc.Server, srv TreeServiceServer) {
	s.RegisterService(&_TreeService_serviceDesc, srv)
}

func _TreeService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/treepb.TreeService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_GetListStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetListStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TreeServiceServer).GetListStream(m, &treeServiceGetListStreamServer{stream})
}

type TreeService_GetListStreamServer interface {
	Send(*NodeInfo) error
	grpc.ServerStream
}

type treeServiceGetListStreamServer struct {
	grpc.ServerStream
}

func (x *treeServiceGetListStreamServer) Send(m *NodeInfo) error {
	return x.ServerStream.SendMsg(m)
}

func _TreeService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/treepb.TreeService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/treepb.TreeService/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_GetInfoSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TreeServiceServer).GetInfoSession(&treeServiceGetInfoSessionServer{stream})
}

type TreeService_GetInfoSessionServer interface {
	Send(*NodeInfo) error
	Recv() (*GetInfoRequest, error)
	grpc.ServerStream
}

type treeServiceGetInfoSessionServer struct {
	grpc.ServerStream
}

func (x *treeServiceGetInfoSessionServer) Send(m *NodeInfo) error {
	return x.ServerStream.SendMsg(m)
}

func (x *treeServiceGetInfoSessionServer) Recv() (*GetInfoRequest, error) {
	m := new(GetInfoRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TreeService_GetMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).GetMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/treepb.TreeService/GetMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).GetMeta(ctx, req.(*GetMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_SetMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).SetMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/treepb.TreeService/SetMeta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).SetMeta(ctx, req.(*SetMetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_DownloadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).DownloadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/treepb.TreeService/DownloadURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).DownloadURL(ctx, req.(*DownloadInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_UploadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).UploadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/treepb.TreeService/UploadURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).UploadURL(ctx, req.(*UploadInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_Copy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).Copy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/treepb.TreeService/Copy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).Copy(ctx, req.(*CopyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/treepb.TreeService/Move",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).Move(ctx, req.(*MoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/treepb.TreeService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TreeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "treepb.TreeService",
	HandlerType: (*TreeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _TreeService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _TreeService_Create_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _TreeService_GetInfo_Handler,
		},
		{
			MethodName: "GetMeta",
			Handler:    _TreeService_GetMeta_Handler,
		},
		{
			MethodName: "SetMeta",
			Handler:    _TreeService_SetMeta_Handler,
		},
		{
			MethodName: "DownloadURL",
			Handler:    _TreeService_DownloadURL_Handler,
		},
		{
			MethodName: "UploadURL",
			Handler:    _TreeService_UploadURL_Handler,
		},
		{
			MethodName: "Copy",
			Handler:    _TreeService_Copy_Handler,
		},
		{
			MethodName: "Move",
			Handler:    _TreeService_Move_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TreeService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetListStream",
			Handler:       _TreeService_GetListStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetInfoSession",
			Handler:       _TreeService_GetInfoSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tree.proto",
}
