// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package datapb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Scope int32

const (
	Scope_Public            Scope = 0
	Scope_Personal          Scope = 1
	Scope_ContextRestricted Scope = 2
)

var Scope_name = map[int32]string{
	0: "Public",
	1: "Personal",
	2: "ContextRestricted",
}

var Scope_value = map[string]int32{
	"Public":            0,
	"Personal":          1,
	"ContextRestricted": 2,
}

func (x Scope) String() string {
	return proto.EnumName(Scope_name, int32(x))
}

func (Scope) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

type AttributeDefinition struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label                string   `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Mime                 string   `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Unique               bool     `protobuf:"varint,5,opt,name=unique,proto3" json:"unique,omitempty"`
	Scope                Scope    `protobuf:"varint,6,opt,name=scope,proto3,enum=datapb.Scope" json:"scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttributeDefinition) Reset()         { *m = AttributeDefinition{} }
func (m *AttributeDefinition) String() string { return proto.CompactTextString(m) }
func (*AttributeDefinition) ProtoMessage()    {}
func (*AttributeDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *AttributeDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttributeDefinition.Unmarshal(m, b)
}
func (m *AttributeDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttributeDefinition.Marshal(b, m, deterministic)
}
func (m *AttributeDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttributeDefinition.Merge(m, src)
}
func (m *AttributeDefinition) XXX_Size() int {
	return xxx_messageInfo_AttributeDefinition.Size(m)
}
func (m *AttributeDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_AttributeDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_AttributeDefinition proto.InternalMessageInfo

func (m *AttributeDefinition) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AttributeDefinition) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *AttributeDefinition) GetMime() string {
	if m != nil {
		return m.Mime
	}
	return ""
}

func (m *AttributeDefinition) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AttributeDefinition) GetUnique() bool {
	if m != nil {
		return m.Unique
	}
	return false
}

func (m *AttributeDefinition) GetScope() Scope {
	if m != nil {
		return m.Scope
	}
	return Scope_Public
}

type Attribute struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Context              string   `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	Mime                 string   `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
	Uri                  string   `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attribute) Reset()         { *m = Attribute{} }
func (m *Attribute) String() string { return proto.CompactTextString(m) }
func (*Attribute) ProtoMessage()    {}
func (*Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{1}
}

func (m *Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attribute.Unmarshal(m, b)
}
func (m *Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attribute.Marshal(b, m, deterministic)
}
func (m *Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attribute.Merge(m, src)
}
func (m *Attribute) XXX_Size() int {
	return xxx_messageInfo_Attribute.Size(m)
}
func (m *Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_Attribute proto.InternalMessageInfo

func (m *Attribute) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Attribute) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *Attribute) GetMime() string {
	if m != nil {
		return m.Mime
	}
	return ""
}

func (m *Attribute) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

type Query struct {
	Subject              string   `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	AttributeIds         []string `protobuf:"bytes,2,rep,name=attribute_ids,json=attributeIds,proto3" json:"attribute_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{2}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Query) GetAttributeIds() []string {
	if m != nil {
		return m.AttributeIds
	}
	return nil
}

type SetAttributesRequest struct {
	Subject              string       `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Attributes           []*Attribute `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SetAttributesRequest) Reset()         { *m = SetAttributesRequest{} }
func (m *SetAttributesRequest) String() string { return proto.CompactTextString(m) }
func (*SetAttributesRequest) ProtoMessage()    {}
func (*SetAttributesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{3}
}

func (m *SetAttributesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAttributesRequest.Unmarshal(m, b)
}
func (m *SetAttributesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAttributesRequest.Marshal(b, m, deterministic)
}
func (m *SetAttributesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAttributesRequest.Merge(m, src)
}
func (m *SetAttributesRequest) XXX_Size() int {
	return xxx_messageInfo_SetAttributesRequest.Size(m)
}
func (m *SetAttributesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAttributesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAttributesRequest proto.InternalMessageInfo

func (m *SetAttributesRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *SetAttributesRequest) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type SetAttributesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAttributesResponse) Reset()         { *m = SetAttributesResponse{} }
func (m *SetAttributesResponse) String() string { return proto.CompactTextString(m) }
func (*SetAttributesResponse) ProtoMessage()    {}
func (*SetAttributesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{4}
}

func (m *SetAttributesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAttributesResponse.Unmarshal(m, b)
}
func (m *SetAttributesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAttributesResponse.Marshal(b, m, deterministic)
}
func (m *SetAttributesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAttributesResponse.Merge(m, src)
}
func (m *SetAttributesResponse) XXX_Size() int {
	return xxx_messageInfo_SetAttributesResponse.Size(m)
}
func (m *SetAttributesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAttributesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetAttributesResponse proto.InternalMessageInfo

type GetAttributesRequest struct {
	Query                *Query   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAttributesRequest) Reset()         { *m = GetAttributesRequest{} }
func (m *GetAttributesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAttributesRequest) ProtoMessage()    {}
func (*GetAttributesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{5}
}

func (m *GetAttributesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAttributesRequest.Unmarshal(m, b)
}
func (m *GetAttributesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAttributesRequest.Marshal(b, m, deterministic)
}
func (m *GetAttributesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAttributesRequest.Merge(m, src)
}
func (m *GetAttributesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAttributesRequest.Size(m)
}
func (m *GetAttributesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAttributesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAttributesRequest proto.InternalMessageInfo

func (m *GetAttributesRequest) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

type GetAttributesResponse struct {
	Attributes           []*Attribute `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetAttributesResponse) Reset()         { *m = GetAttributesResponse{} }
func (m *GetAttributesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAttributesResponse) ProtoMessage()    {}
func (*GetAttributesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{6}
}

func (m *GetAttributesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAttributesResponse.Unmarshal(m, b)
}
func (m *GetAttributesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAttributesResponse.Marshal(b, m, deterministic)
}
func (m *GetAttributesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAttributesResponse.Merge(m, src)
}
func (m *GetAttributesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAttributesResponse.Size(m)
}
func (m *GetAttributesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAttributesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAttributesResponse proto.InternalMessageInfo

func (m *GetAttributesResponse) GetAttributes() []*Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type DeleteAttributesRequest struct {
	Query                *Query   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAttributesRequest) Reset()         { *m = DeleteAttributesRequest{} }
func (m *DeleteAttributesRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAttributesRequest) ProtoMessage()    {}
func (*DeleteAttributesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{7}
}

func (m *DeleteAttributesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAttributesRequest.Unmarshal(m, b)
}
func (m *DeleteAttributesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAttributesRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAttributesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAttributesRequest.Merge(m, src)
}
func (m *DeleteAttributesRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAttributesRequest.Size(m)
}
func (m *DeleteAttributesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAttributesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAttributesRequest proto.InternalMessageInfo

func (m *DeleteAttributesRequest) GetQuery() *Query {
	if m != nil {
		return m.Query
	}
	return nil
}

type DeleteAttributesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAttributesResponse) Reset()         { *m = DeleteAttributesResponse{} }
func (m *DeleteAttributesResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAttributesResponse) ProtoMessage()    {}
func (*DeleteAttributesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{8}
}

func (m *DeleteAttributesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAttributesResponse.Unmarshal(m, b)
}
func (m *DeleteAttributesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAttributesResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAttributesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAttributesResponse.Merge(m, src)
}
func (m *DeleteAttributesResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAttributesResponse.Size(m)
}
func (m *DeleteAttributesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAttributesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAttributesResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("datapb.Scope", Scope_name, Scope_value)
	proto.RegisterType((*AttributeDefinition)(nil), "datapb.AttributeDefinition")
	proto.RegisterType((*Attribute)(nil), "datapb.Attribute")
	proto.RegisterType((*Query)(nil), "datapb.Query")
	proto.RegisterType((*SetAttributesRequest)(nil), "datapb.SetAttributesRequest")
	proto.RegisterType((*SetAttributesResponse)(nil), "datapb.SetAttributesResponse")
	proto.RegisterType((*GetAttributesRequest)(nil), "datapb.GetAttributesRequest")
	proto.RegisterType((*GetAttributesResponse)(nil), "datapb.GetAttributesResponse")
	proto.RegisterType((*DeleteAttributesRequest)(nil), "datapb.DeleteAttributesRequest")
	proto.RegisterType((*DeleteAttributesResponse)(nil), "datapb.DeleteAttributesResponse")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcd, 0x8e, 0xd3, 0x3c,
	0x14, 0x86, 0xbf, 0xa4, 0x93, 0x7e, 0xd3, 0xd3, 0x1f, 0xb5, 0xa6, 0xa5, 0x51, 0x35, 0x88, 0x28,
	0xdd, 0x54, 0x5d, 0xb4, 0xa2, 0x6c, 0xd0, 0x20, 0x21, 0x21, 0x2a, 0x22, 0x58, 0x0d, 0xe9, 0x92,
	0x05, 0x72, 0x92, 0x43, 0x65, 0x94, 0x89, 0xd3, 0xd8, 0x91, 0x60, 0xcb, 0x2d, 0x70, 0x1f, 0xdc,
	0x04, 0x97, 0xc0, 0x2d, 0x70, 0x21, 0x28, 0x76, 0x12, 0x86, 0x4e, 0x3a, 0x1a, 0xb1, 0xf3, 0xf9,
	0xc9, 0xfb, 0xbc, 0xe7, 0xd8, 0x0a, 0x40, 0x44, 0x25, 0x5d, 0xa5, 0x19, 0x97, 0x9c, 0xb4, 0x8b,
	0x73, 0x1a, 0xcc, 0x2e, 0xf6, 0x9c, 0xef, 0x63, 0x5c, 0xd3, 0x94, 0xad, 0x69, 0x92, 0x70, 0x49,
	0x25, 0xe3, 0x89, 0xd0, 0x5d, 0xee, 0x77, 0x03, 0x1e, 0xbc, 0x94, 0x32, 0x63, 0x41, 0x2e, 0x71,
	0x8b, 0x1f, 0x59, 0xc2, 0x8a, 0x32, 0x19, 0x80, 0xc9, 0x22, 0xdb, 0x70, 0x8c, 0x45, 0xc7, 0x37,
	0x59, 0x44, 0xc6, 0x60, 0xc5, 0x34, 0xc0, 0xd8, 0x36, 0x55, 0x4a, 0x07, 0x84, 0xc0, 0xd9, 0x35,
	0xbb, 0x46, 0xbb, 0xa5, 0x92, 0xea, 0x4c, 0x1c, 0xe8, 0x46, 0x28, 0xc2, 0x8c, 0xa5, 0x85, 0x90,
	0x7d, 0xa6, 0x4a, 0x37, 0x53, 0xe4, 0x21, 0xb4, 0xf3, 0x84, 0x1d, 0x72, 0xb4, 0x2d, 0xc7, 0x58,
	0x9c, 0xfb, 0x65, 0x44, 0xe6, 0x60, 0x89, 0x90, 0xa7, 0x68, 0xb7, 0x1d, 0x63, 0x31, 0xd8, 0xf4,
	0x57, 0x7a, 0x82, 0xd5, 0xae, 0x48, 0xfa, 0xba, 0xe6, 0xbe, 0x87, 0x4e, 0xed, 0xf7, 0x96, 0x4b,
	0x1b, 0xfe, 0x0f, 0x79, 0x22, 0xf1, 0xb3, 0x2c, 0x7d, 0x56, 0x61, 0xa3, 0xd3, 0x21, 0xb4, 0xf2,
	0x8c, 0x95, 0x0e, 0x8b, 0xa3, 0xfb, 0x1a, 0xac, 0x77, 0x39, 0x66, 0x5f, 0x0a, 0x21, 0x91, 0x07,
	0x9f, 0x30, 0x94, 0xa5, 0x7a, 0x15, 0x92, 0x39, 0xf4, 0x69, 0xc5, 0xff, 0xc0, 0x22, 0x61, 0x9b,
	0x4e, 0x6b, 0xd1, 0xf1, 0x7b, 0x75, 0xf2, 0x4d, 0x24, 0xdc, 0x10, 0xc6, 0x3b, 0x94, 0xb5, 0x4f,
	0xe1, 0xe3, 0x21, 0x47, 0x21, 0xef, 0x90, 0x7d, 0x02, 0x50, 0x2b, 0x68, 0xcd, 0xee, 0x66, 0x54,
	0x2d, 0xa0, 0x16, 0xf2, 0x6f, 0x34, 0xb9, 0x53, 0x98, 0x1c, 0x41, 0x44, 0xca, 0x13, 0x81, 0xee,
	0x73, 0x18, 0x7b, 0x4d, 0xf4, 0x39, 0x58, 0x87, 0x62, 0x3a, 0xc5, 0xee, 0xfe, 0xd9, 0xaf, 0x1a,
	0xd9, 0xd7, 0x35, 0xf7, 0x2d, 0x4c, 0xbc, 0x26, 0xd5, 0x23, 0x87, 0xc6, 0x7d, 0x1c, 0xbe, 0x80,
	0xe9, 0x16, 0x63, 0x94, 0xf8, 0x8f, 0x5e, 0x66, 0x60, 0xdf, 0xfe, 0x5e, 0xdb, 0x59, 0x3e, 0x03,
	0x4b, 0xbd, 0x0b, 0x02, 0xd0, 0xbe, 0xca, 0x83, 0x98, 0x85, 0xc3, 0xff, 0x48, 0x0f, 0xce, 0xaf,
	0x30, 0x13, 0x3c, 0xa1, 0xf1, 0xd0, 0x20, 0x13, 0x18, 0xbd, 0xd2, 0xd7, 0xef, 0xa3, 0x90, 0x19,
	0x0b, 0x25, 0x46, 0x43, 0x73, 0xf3, 0xc3, 0x84, 0xce, 0x96, 0x4a, 0xba, 0x93, 0x3c, 0x43, 0x12,
	0x40, 0xff, 0xaf, 0x2d, 0x92, 0x8b, 0xfa, 0xd9, 0x35, 0xec, 0x70, 0xf6, 0xe8, 0x44, 0xb5, 0x5c,
	0xfd, 0xf8, 0xeb, 0xcf, 0x5f, 0xdf, 0xcc, 0x81, 0xdb, 0x59, 0x17, 0x6d, 0x6b, 0x81, 0xf2, 0xd2,
	0x58, 0x16, 0x0c, 0xaf, 0x99, 0xe1, 0xdd, 0xc9, 0xf0, 0xee, 0xc3, 0xd8, 0x6b, 0x46, 0x02, 0xc3,
	0xe3, 0x5d, 0x91, 0xc7, 0x95, 0xd0, 0x89, 0x5b, 0x98, 0x39, 0xa7, 0x1b, 0x4a, 0xd8, 0x54, 0xc1,
	0x46, 0x6e, 0x4f, 0xc3, 0x22, 0xd5, 0x77, 0x69, 0x2c, 0x83, 0xb6, 0xfa, 0x7f, 0x3c, 0xfd, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0xbc, 0x60, 0x15, 0x1d, 0x73, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DataStoreClient is the client API for DataStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataStoreClient interface {
	SetAttributes(ctx context.Context, in *SetAttributesRequest, opts ...grpc.CallOption) (*SetAttributesResponse, error)
	GetAttributes(ctx context.Context, in *GetAttributesRequest, opts ...grpc.CallOption) (*GetAttributesResponse, error)
	DeleteAttributes(ctx context.Context, in *DeleteAttributesRequest, opts ...grpc.CallOption) (*DeleteAttributesResponse, error)
}

type dataStoreClient struct {
	cc *grpc.ClientConn
}

func NewDataStoreClient(cc *grpc.ClientConn) DataStoreClient {
	return &dataStoreClient{cc}
}

func (c *dataStoreClient) SetAttributes(ctx context.Context, in *SetAttributesRequest, opts ...grpc.CallOption) (*SetAttributesResponse, error) {
	out := new(SetAttributesResponse)
	err := c.cc.Invoke(ctx, "/datapb.DataStore/SetAttributes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStoreClient) GetAttributes(ctx context.Context, in *GetAttributesRequest, opts ...grpc.CallOption) (*GetAttributesResponse, error) {
	out := new(GetAttributesResponse)
	err := c.cc.Invoke(ctx, "/datapb.DataStore/GetAttributes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataStoreClient) DeleteAttributes(ctx context.Context, in *DeleteAttributesRequest, opts ...grpc.CallOption) (*DeleteAttributesResponse, error) {
	out := new(DeleteAttributesResponse)
	err := c.cc.Invoke(ctx, "/datapb.DataStore/DeleteAttributes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataStoreServer is the server API for DataStore service.
type DataStoreServer interface {
	SetAttributes(context.Context, *SetAttributesRequest) (*SetAttributesResponse, error)
	GetAttributes(context.Context, *GetAttributesRequest) (*GetAttributesResponse, error)
	DeleteAttributes(context.Context, *DeleteAttributesRequest) (*DeleteAttributesResponse, error)
}

func RegisterDataStoreServer(s *grpc.Server, srv DataStoreServer) {
	s.RegisterService(&_DataStore_serviceDesc, srv)
}

func _DataStore_SetAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStoreServer).SetAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datapb.DataStore/SetAttributes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStoreServer).SetAttributes(ctx, req.(*SetAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStore_GetAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStoreServer).GetAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datapb.DataStore/GetAttributes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStoreServer).GetAttributes(ctx, req.(*GetAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataStore_DeleteAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataStoreServer).DeleteAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datapb.DataStore/DeleteAttributes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataStoreServer).DeleteAttributes(ctx, req.(*DeleteAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "datapb.DataStore",
	HandlerType: (*DataStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetAttributes",
			Handler:    _DataStore_SetAttributes_Handler,
		},
		{
			MethodName: "GetAttributes",
			Handler:    _DataStore_GetAttributes_Handler,
		},
		{
			MethodName: "DeleteAttributes",
			Handler:    _DataStore_DeleteAttributes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data.proto",
}
